In [40]:
import math
import os
import time
import re
import requests
import polars as pl

from decorator import append
from dotenv import load_dotenv
from duckdb.experimental.spark.sql.functions import length
from datetime import datetime
from utils.postgres.postgres_connection import PostgresConnection


load_dotenv(override=True)

RIOT_PERSONAL_API_KEY = os.getenv("LOL_PERSONAL_API_KEY")
POSTGRES_LOCAL_URL = os.getenv("POSTGRES_LOCAL_URL")
connection_wrapper = PostgresConnection(POSTGRES_LOCAL_URL)

opening connection

In [2]:
_camel_case_regex = re.compile(
    r"(?<=[a-z])(?=[A-Z])"  # camelCase: survive|Min
    r"|(?<=[A-Z])(?=[A-Z][a-z])"  # acronym: HTML|Parser
    r"|(?<=[a-zA-Z])(?=\d)"  # letter→digit: survive|15
    r"|(?<=\d)(?=[a-zA-Z])"  # digit→letter: 15|min
)


def camel_to_snake(input_str: str) -> str:
    return _camel_case_regex.sub("_", input_str).lower()


def snake_all_keys(json_obj: dict):
    if isinstance(json_obj, dict):
        return {camel_to_snake(key): snake_all_keys(value) for key, value in json_obj.items()}

    if isinstance(json_obj, list):
        return [snake_all_keys(value) for value in json_obj]

    return json_obj

In [3]:
players = pl.read_database_uri("SELECT * FROM players", POSTGRES_LOCAL_URL)
players

shape: (3_100, 5)
┌──────────────────────────────┬──────────────────┬──────────┬────────┬────────────────────────────┐
│ puuid                        ┆ game_name        ┆ tag_line ┆ region ┆ synced_at                  │
│ ---                          ┆ ---              ┆ ---      ┆ ---    ┆ ---                        │
│ str                          ┆ str              ┆ str      ┆ str    ┆ datetime[μs]               │
╞══════════════════════════════╪══════════════════╪══════════╪════════╪════════════════════════════╡
│ x1jqYLksFHSjj-V_dTeZrzR9fFEV ┆ bird raven       ┆ 0000     ┆ EUN1   ┆ 2026-05-31 18:10:37.551072 │
│ Dt…                          ┆                  ┆          ┆        ┆                            │
│ QMPPN4oUrY-FW-BBOZ34yDZZmjgh ┆ KaizokuNoOni     ┆ 2829     ┆ EUN1   ┆ 2026-05-31 18:10:37.860377 │
│ Pa…                          ┆                  ┆          ┆        ┆                            │
│ yf1OVyzGtKFWKAh__NIUFtnEisdo ┆ Nolba            ┆ EUNE     ┆ EUN1   ┆ 2026-05-31 18:10:38.176115 │
│ hM…                          ┆                  ┆          ┆        ┆                            │
│ gw0udTm33m9cDPfENXndpjlXmkHw ┆ Defenser         ┆ EUNE     ┆ EUN1   ┆ 2026-05-31 18:10:38.472933 │
│ xl…                          ┆                  ┆          ┆        ┆                            │
│ tD8QYcsn9jmPaM7AACN9Id2fwgus ┆ Dioklis          ┆ EUNE     ┆ EUN1   ┆ 2026-05-31 18:10:38.757716 │
│ fN…                          ┆                  ┆          ┆        ┆                            │
│ …                            ┆ …                ┆ …        ┆ …      ┆ …                          │
│ dYiEC-ravKg74XNQMp4KsOp4S7aV ┆ black nails      ┆ 988      ┆ EUN1   ┆ 2026-05-31 19:15:39.289847 │
│ lR…                          ┆                  ┆          ┆        ┆                            │
│ ZLw_1J27yiyrFC_UN7-Uck-IyYMB ┆ AleEmotkaZostała ┆ RMJ      ┆ EUN1   ┆ 2026-05-31 19:15:39.630180 │
│ LL…                          ┆                  ┆          ┆        ┆                            │
│ 0CPr6RzHVit2UWf0Cu0EXPbIj77e ┆ chiefelo         ┆ 0314     ┆ EUN1   ┆ 2026-05-31 19:15:39.980448 │
│ ko…                          ┆                  ┆          ┆        ┆                            │
│ voxGacYDhQ3ptNab4tGe6ipPP3nZ ┆ Adam             ┆ RANK1    ┆ EUN1   ┆ 2026-05-31 19:15:40.353129 │
│ fc…                          ┆                  ┆          ┆        ┆                            │
│ eMwumb2gCUrYSrSf3D1t_9CyIv3k ┆ RAKIQ V NARGATA  ┆ WAGMI    ┆ EUN1   ┆ 2026-05-31 19:17:14.901659 │
│ PH…                          ┆                  ┆          ┆        ┆                            │
└──────────────────────────────┴──────────────────┴──────────┴────────┴────────────────────────────┘

In [29]:
from datetime import date


BASE_EUN1_URL = "https://eun1.api.riotgames.com"

headers = {
    'X-Riot-Token': RIOT_PERSONAL_API_KEY
}

def get_player_challenges(puuid: str):

    player_challanges_url =f"{BASE_EUN1_URL}/lol/challenges/v1/player-data/{puuid}"
    response_challanges = requests.get(player_challanges_url,headers=headers)

    if response_challanges.status_code != 200:
        print("request failed with status code on getting player challanges", response_challanges.status_code)
        return response_challanges.status_code

    response_challanges_json = response_challanges.json()

    all_player_challenges = []

    for challenges_player in response_challanges_json["challenges"]:

        int_achieved_time=challenges_player.get("achievedTime")

        player_challenges = {
           "puuid": puuid,
           "challenge_id":challenges_player.get("challengeId"),
           "percentile":challenges_player.get("percentile"),
           "players_in_level":challenges_player.get("playersInLevel",None),
           "achieved_time":datetime.fromtimestamp(int_achieved_time // 1000) if int_achieved_time else None,
           "value":challenges_player.get("value"),
           "level":challenges_player.get("level"),
           "position":challenges_player.get("position",None),
        }
        all_player_challenges.append(player_challenges)
    return all_player_challenges

get_player_challenges(players["puuid"][0])

[{'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 0,
  'percentile': 0.335,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 6, 17, 22, 1),
  'value': 3365.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 1,
  'percentile': 0.306,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2025, 10, 31, 2, 57, 14),
  'value': 300.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2,
  'percentile': 0.302,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 11, 21, 46, 23),
  'value': 840.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 3,
  'percentile': 0.299,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 3, 21, 14, 32),
  'value': 805.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 4,
  'percentile': 0.345,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 23, 2, 57, 28),
  'value': 695.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 5,
  'percentile': 0.196,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2024, 6, 10, 20, 42, 49),
  'value': 725.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 302100,
  'percentile': 0.367,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 10, 29, 13, 34, 19),
  'value': 60.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 302101,
  'percentile': 0.291,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2024, 2, 25, 22, 40, 10),
  'value': 4.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 302102,
  'percentile': 0.143,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2024, 2, 8, 0, 48, 29),
  'value': 70.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 302106,
  'percentile': 0.229,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 10, 29, 12, 42, 45),
  'value': 36.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 203303,
  'percentile': 0.225,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 10, 29, 12, 42, 45),
  'value': 257.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 203302,
  'percentile': 0.212,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 10, 13, 16, 56, 38),
  'value': 261.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 203301,
  'percentile': 0.2,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2024, 2, 16, 3, 0, 32),
  'value': 379.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 203300,
  'percentile': 0.214,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 10, 29, 13, 34, 19),
  'value': 100.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 301100,
  'percentile': 0.298,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 31, 22, 21, 25),
  'value': 125.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 301101,
  'percentile': 0.127,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 27, 18, 31, 25),
  'value': 47.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 203305,
  'percentile': 0.15,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 6, 20, 14, 51),
  'value': 27.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 301102,
  'percentile': 0.265,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2025, 11, 1, 0, 2, 24),
  'value': 4.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510006,
  'percentile': 0.219,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 11, 19, 36, 10),
  'value': 1.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510005,
  'percentile': 0.183,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 21, 3, 41, 2),
  'value': 11.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510004,
  'percentile': 0.106,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 11, 19, 36, 10),
  'value': 1.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 301104,
  'percentile': 0.223,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 27, 19, 5, 42),
  'value': 11.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510003,
  'percentile': 0.148,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 11, 19, 36, 10),
  'value': 5.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 301105,
  'percentile': 0.231,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 27, 23, 25, 42),
  'value': 14.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 301106,
  'percentile': 0.226,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 31, 21, 30, 33),
  'value': 2.0,
  'level': 'DIAMOND',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510001,
  'percentile': 0.208,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 21, 3, 41, 2),
  'value': 36.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510000,
  'percentile': 0.232,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 11, 19, 36, 10),
  'value': 105.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 202303,
  'percentile': 0.263,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 18, 21, 2, 2),
  'value': 3.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510011,
  'percentile': 0.188,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 11, 19, 36, 10),
  'value': 7.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 202302,
  'percentile': 0.292,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 16, 19, 35, 22),
  'value': 1.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510010,
  'percentile': 0.211,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 24, 0, 32, 2),
  'value': 11.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 202301,
  'percentile': 0.24,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 18, 21, 2, 2),
  'value': 1.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510009,
  'percentile': 0.309,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 11, 19, 36, 10),
  'value': 2.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 202300,
  'percentile': 0.325,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 18, 21, 20, 26),
  'value': 60.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 402502,
  'percentile': 0.327,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 23, 23, 53, 19),
  'value': 1012.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 402503,
  'percentile': 0.228,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 8, 4, 21, 52, 17),
  'value': 42176.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 202305,
  'percentile': 0.269,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2024, 2, 14, 19, 41, 32),
  'value': 24.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 402500,
  'percentile': 0.321,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 24, 0, 25, 12),
  'value': 40.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 402501,
  'percentile': 0.35,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2025, 11, 4, 2, 17, 7),
  'value': 6249.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023003,
  'percentile': 0.216,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 31, 20, 44, 45),
  'value': 45.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023000,
  'percentile': 0.262,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 24, 20, 44, 27),
  'value': 175.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023001,
  'percentile': 0.137,
  'players_in_level': 1933503,
  'achieved_time': datetime.datetime(2023, 7, 24, 20, 13, 37),
  'value': 1.0,
  'level': 'MASTER',
  'position': 1465596},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 210003,
  'percentile': 0.445,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2026, 3, 17, 6, 50, 10),
  'value': 2.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 210001,
  'percentile': 0.372,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2026, 3, 17, 6, 50, 10),
  'value': 1.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 210000,
  'percentile': 0.306,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2024, 2, 8, 1, 31, 18),
  'value': 35.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 210005,
  'percentile': 0.205,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2024, 2, 8, 0, 48, 29),
  'value': 33.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 402000,
  'percentile': 0.221,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2025, 11, 3, 2, 49, 42),
  'value': 590.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 210004,
  'percentile': 0.283,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 12, 19, 52, 15),
  'value': 8.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 103000,
  'percentile': 0.235,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 29, 16, 5, 54),
  'value': 275.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022014,
  'percentile': 0.107,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 25, 22, 2, 28),
  'value': 4.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022015,
  'percentile': 0.109,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 27, 23, 59, 21),
  'value': 58.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022010,
  'percentile': 0.046,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 3, 21, 23, 40),
  'value': 13.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022008,
  'percentile': 0.156,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 12, 22, 15, 23),
  'value': 1.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022009,
  'percentile': 0.119,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 27, 23, 59, 21),
  'value': 197.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022006,
  'percentile': 0.117,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 16, 18, 56, 44),
  'value': 5.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022007,
  'percentile': 0.099,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 16, 19, 35, 22),
  'value': 1.0,
  'level': 'DIAMOND',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022004,
  'percentile': 0.055,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 23, 21, 50, 43),
  'value': 4.0,
  'level': 'DIAMOND',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022005,
  'percentile': 0.171,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 22, 17, 25),
  'value': 4.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 401000,
  'percentile': 0.205,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2025, 10, 31, 2, 2, 49),
  'value': 175.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022000,
  'percentile': 0.108,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 23, 22, 8, 58),
  'value': 275.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023019,
  'percentile': 0.277,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 27, 23, 25, 42),
  'value': 24.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023016,
  'percentile': 0.269,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 25, 23, 40, 13),
  'value': 285.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023017,
  'percentile': 0.194,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 10, 29, 12, 42, 45),
  'value': 59.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023015,
  'percentile': 0.205,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 8, 2, 23, 59, 1),
  'value': 3.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 302200,
  'percentile': 0.338,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 28, 0, 22, 4),
  'value': 20.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023010,
  'percentile': 0.139,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 30, 0, 27, 54),
  'value': 4.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 302201,
  'percentile': 0.298,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 25, 22, 2, 28),
  'value': 4.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 302202,
  'percentile': 0.295,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 10, 9, 16, 11, 19),
  'value': 9.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023008,
  'percentile': 0.257,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 8, 4, 20, 55, 40),
  'value': 2.0,

In [37]:
player_challenges_arr = []

current_index = 0
for player in players.iter_rows(named=True):
    current_index += 1
    if current_index % 50 == 0:
        print(f"progress {math.floor(current_index / len(players) * 100)}%")
    try:
        player_challenges = get_player_challenges(player["puuid"])
        while player_challenges == 429:
            print("retrying after getting rate limited")
            time.sleep(121)
            player_challenges = get_player_challenges(player["puuid"])

        player_challenges_arr.extend(player_challenges)

    except Exception as e:
        print(f"Error fetching snapshot for {player['puuid']}: {e}")
        continue

player_challenges_arr

progress 1%
progress 3%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 4%
progress 6%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 8%
progress 9%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 11%
progress 12%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 14%
progress 16%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 17%
progress 19%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 20%
progress 22%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 24%
progress 25%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 27%
progress 29%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 30%
progress 32%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 33%
progress 35%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 37%
progress 38%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 40%
progress 41%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 43%
progress 45%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 46%
progress 48%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 50%
progress 51%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 53%
progress 54%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 56%
progress 58%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 59%
progress 61%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 62%
progress 64%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 66%
progress 67%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 69%
progress 70%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 72%
progress 74%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 75%
progress 77%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 79%
progress 80%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 82%
progress 83%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 85%
progress 87%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 88%
progress 90%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 91%
progress 93%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 95%
progress 96%
request failed with status code on getting player challanges 429
retrying after getting rate limited
progress 98%
progress 100%

[{'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 0,
  'percentile': 0.335,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 6, 17, 22, 1),
  'value': 3365.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 1,
  'percentile': 0.306,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2025, 10, 31, 2, 57, 14),
  'value': 300.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2,
  'percentile': 0.302,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 11, 21, 46, 23),
  'value': 840.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 3,
  'percentile': 0.299,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 3, 21, 14, 32),
  'value': 805.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 4,
  'percentile': 0.345,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 23, 2, 57, 28),
  'value': 695.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 5,
  'percentile': 0.196,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2024, 6, 10, 20, 42, 49),
  'value': 725.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 302100,
  'percentile': 0.367,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 10, 29, 13, 34, 19),
  'value': 60.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 302101,
  'percentile': 0.291,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2024, 2, 25, 22, 40, 10),
  'value': 4.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 302102,
  'percentile': 0.143,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2024, 2, 8, 0, 48, 29),
  'value': 70.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 302106,
  'percentile': 0.229,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 10, 29, 12, 42, 45),
  'value': 36.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 203303,
  'percentile': 0.225,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 10, 29, 12, 42, 45),
  'value': 257.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 203302,
  'percentile': 0.212,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 10, 13, 16, 56, 38),
  'value': 261.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 203301,
  'percentile': 0.2,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2024, 2, 16, 3, 0, 32),
  'value': 379.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 203300,
  'percentile': 0.214,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 10, 29, 13, 34, 19),
  'value': 100.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 301100,
  'percentile': 0.298,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 31, 22, 21, 25),
  'value': 125.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 301101,
  'percentile': 0.127,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 27, 18, 31, 25),
  'value': 47.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 203305,
  'percentile': 0.15,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 6, 20, 14, 51),
  'value': 27.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 301102,
  'percentile': 0.265,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2025, 11, 1, 0, 2, 24),
  'value': 4.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510006,
  'percentile': 0.219,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 11, 19, 36, 10),
  'value': 1.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510005,
  'percentile': 0.183,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 21, 3, 41, 2),
  'value': 11.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510004,
  'percentile': 0.106,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 11, 19, 36, 10),
  'value': 1.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 301104,
  'percentile': 0.223,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 27, 19, 5, 42),
  'value': 11.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510003,
  'percentile': 0.148,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 11, 19, 36, 10),
  'value': 5.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 301105,
  'percentile': 0.231,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 27, 23, 25, 42),
  'value': 14.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 301106,
  'percentile': 0.226,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 31, 21, 30, 33),
  'value': 2.0,
  'level': 'DIAMOND',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510001,
  'percentile': 0.208,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 21, 3, 41, 2),
  'value': 36.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510000,
  'percentile': 0.232,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 11, 19, 36, 10),
  'value': 105.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 202303,
  'percentile': 0.263,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 18, 21, 2, 2),
  'value': 3.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510011,
  'percentile': 0.188,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 11, 19, 36, 10),
  'value': 7.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 202302,
  'percentile': 0.292,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 16, 19, 35, 22),
  'value': 1.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510010,
  'percentile': 0.211,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 24, 0, 32, 2),
  'value': 11.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 202301,
  'percentile': 0.24,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 18, 21, 2, 2),
  'value': 1.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 510009,
  'percentile': 0.309,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 11, 19, 36, 10),
  'value': 2.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 202300,
  'percentile': 0.325,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 18, 21, 20, 26),
  'value': 60.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 402502,
  'percentile': 0.327,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 23, 23, 53, 19),
  'value': 1012.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 402503,
  'percentile': 0.228,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 8, 4, 21, 52, 17),
  'value': 42176.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 202305,
  'percentile': 0.269,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2024, 2, 14, 19, 41, 32),
  'value': 24.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 402500,
  'percentile': 0.321,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 24, 0, 25, 12),
  'value': 40.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 402501,
  'percentile': 0.35,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2025, 11, 4, 2, 17, 7),
  'value': 6249.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023003,
  'percentile': 0.216,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 31, 20, 44, 45),
  'value': 45.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023000,
  'percentile': 0.262,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 24, 20, 44, 27),
  'value': 175.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023001,
  'percentile': 0.137,
  'players_in_level': 1933503,
  'achieved_time': datetime.datetime(2023, 7, 24, 20, 13, 37),
  'value': 1.0,
  'level': 'MASTER',
  'position': 1465596},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 210003,
  'percentile': 0.445,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2026, 3, 17, 6, 50, 10),
  'value': 2.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 210001,
  'percentile': 0.372,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2026, 3, 17, 6, 50, 10),
  'value': 1.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 210000,
  'percentile': 0.306,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2024, 2, 8, 1, 31, 18),
  'value': 35.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 210005,
  'percentile': 0.205,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2024, 2, 8, 0, 48, 29),
  'value': 33.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 402000,
  'percentile': 0.221,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2025, 11, 3, 2, 49, 42),
  'value': 590.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 210004,
  'percentile': 0.283,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 12, 19, 52, 15),
  'value': 8.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 103000,
  'percentile': 0.235,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 29, 16, 5, 54),
  'value': 275.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022014,
  'percentile': 0.107,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 25, 22, 2, 28),
  'value': 4.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022015,
  'percentile': 0.109,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 27, 23, 59, 21),
  'value': 58.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022010,
  'percentile': 0.046,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 3, 21, 23, 40),
  'value': 13.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022008,
  'percentile': 0.156,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 12, 22, 15, 23),
  'value': 1.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022009,
  'percentile': 0.119,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 27, 23, 59, 21),
  'value': 197.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022006,
  'percentile': 0.117,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 16, 18, 56, 44),
  'value': 5.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022007,
  'percentile': 0.099,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 16, 19, 35, 22),
  'value': 1.0,
  'level': 'DIAMOND',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022004,
  'percentile': 0.055,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 23, 21, 50, 43),
  'value': 4.0,
  'level': 'DIAMOND',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022005,
  'percentile': 0.171,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 22, 17, 25),
  'value': 4.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 401000,
  'percentile': 0.205,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2025, 10, 31, 2, 2, 49),
  'value': 175.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2022000,
  'percentile': 0.108,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 7, 23, 22, 8, 58),
  'value': 275.0,
  'level': 'GOLD',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023019,
  'percentile': 0.277,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 27, 23, 25, 42),
  'value': 24.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023016,
  'percentile': 0.269,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 25, 23, 40, 13),
  'value': 285.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023017,
  'percentile': 0.194,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 10, 29, 12, 42, 45),
  'value': 59.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023015,
  'percentile': 0.205,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 8, 2, 23, 59, 1),
  'value': 3.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 302200,
  'percentile': 0.338,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 28, 0, 22, 4),
  'value': 20.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023010,
  'percentile': 0.139,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 7, 30, 0, 27, 54),
  'value': 4.0,
  'level': 'BRONZE',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 302201,
  'percentile': 0.298,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 5, 25, 22, 2, 28),
  'value': 4.0,
  'level': 'IRON',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 302202,
  'percentile': 0.295,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2022, 10, 9, 16, 11, 19),
  'value': 9.0,
  'level': 'SILVER',
  'position': None},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'challenge_id': 2023008,
  'percentile': 0.257,
  'players_in_level': None,
  'achieved_time': datetime.datetime(2023, 8, 4, 20, 55, 40),
  'value': 2.0,

In [38]:
player_challenges_df=pl.DataFrame(player_challenges_arr)
player_challenges_df

shape: (910_797, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬──────────┐
│ puuid      ┆ challenge_ ┆ percentile ┆ players_in ┆ achieved_t ┆ value     ┆ level    ┆ position │
│ ---        ┆ id         ┆ ---        ┆ _level     ┆ ime        ┆ ---       ┆ ---      ┆ ---      │
│ str        ┆ ---        ┆ f64        ┆ ---        ┆ ---        ┆ f64       ┆ str      ┆ i64      │
│            ┆ i64        ┆            ┆ i64        ┆ datetime[μ ┆           ┆          ┆          │
│            ┆            ┆            ┆            ┆ s]         ┆           ┆          ┆          │
╞════════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪══════════╡
│ x1jqYLksFH ┆ 0          ┆ 0.335      ┆ null       ┆ 2022-07-06 ┆ 3365.0    ┆ SILVER   ┆ null     │
│ Sjj-V_dTeZ ┆            ┆            ┆            ┆ 17:22:01   ┆           ┆          ┆          │
│ rzR9fFEVDt ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ …          ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ x1jqYLksFH ┆ 1          ┆ 0.306      ┆ null       ┆ 2025-10-31 ┆ 300.0     ┆ SILVER   ┆ null     │
│ Sjj-V_dTeZ ┆            ┆            ┆            ┆ 02:57:14   ┆           ┆          ┆          │
│ rzR9fFEVDt ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ …          ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ x1jqYLksFH ┆ 2          ┆ 0.302      ┆ null       ┆ 2022-07-11 ┆ 840.0     ┆ SILVER   ┆ null     │
│ Sjj-V_dTeZ ┆            ┆            ┆            ┆ 21:46:23   ┆           ┆          ┆          │
│ rzR9fFEVDt ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ …          ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ x1jqYLksFH ┆ 3          ┆ 0.299      ┆ null       ┆ 2022-07-03 ┆ 805.0     ┆ SILVER   ┆ null     │
│ Sjj-V_dTeZ ┆            ┆            ┆            ┆ 21:14:32   ┆           ┆          ┆          │
│ rzR9fFEVDt ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ …          ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ x1jqYLksFH ┆ 4          ┆ 0.345      ┆ null       ┆ 2022-07-23 ┆ 695.0     ┆ SILVER   ┆ null     │
│ Sjj-V_dTeZ ┆            ┆            ┆            ┆ 02:57:28   ┆           ┆          ┆          │
│ rzR9fFEVDt ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ …          ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …        ┆ …        │
│ eMwumb2gCU ┆ 402403     ┆ 0.271      ┆ null       ┆ 2026-06-06 ┆ 14.0      ┆ IRON     ┆ null     │
│ rYSrSf3D1t ┆            ┆            ┆            ┆ 00:44:26   ┆           ┆          ┆          │
│ _9CyIv3kPH ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ …          ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ eMwumb2gCU ┆ 402400     ┆ 0.157      ┆ null       ┆ 2026-05-09 ┆ 270.0     ┆ PLATINUM ┆ null     │
│ rYSrSf3D1t ┆            ┆            ┆            ┆ 02:24:52   ┆           ┆          ┆          │
│ _9CyIv3kPH ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ …          ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ eMwumb2gCU ┆ 402401     ┆ 0.098      ┆ null       ┆ 2026-05-23 ┆ 1494.0    ┆ DIAMOND  ┆ null     │
│ rYSrSf3D1t ┆            ┆            ┆            ┆ 13:19:38   ┆           ┆          ┆          │
│ _9CyIv3kPH ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ …          ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ eMwumb2gCU ┆ 402408     ┆ 0.14       ┆ null       ┆ 2026-05-09 ┆ 135416.0  ┆ PLATINUM ┆ null     │
│ rYSrSf3D1t ┆            ┆            ┆            ┆ 01:57:42   ┆           ┆          ┆          │
│ _9CyIv3kPH ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ …          ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ eMwumb2gCU ┆ 402409     ┆ 0.102      ┆ null       ┆ 2026-06-04 ┆ 7.821033e ┆ DIAMOND  ┆ null     │
│ rYSrSf3D1t ┆            ┆            ┆            ┆ 13:17:00   ┆ 6         ┆          ┆          │
│ _9CyIv3kPH ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
│ …          ┆            ┆            ┆            ┆            ┆           ┆          ┆          │
└────────────┴────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴──────────┘

In [41]:
connection_wrapper.upsert_dataframe_dto_safe(player_challenges_df, "challenges", ["puuid","challenge_id"])

0