In [1]:
import math
import os
import time
import re
import requests
import polars as pl

from decorator import append
from dotenv import load_dotenv
from duckdb.experimental.spark.sql.functions import length
from datetime import datetime
from utils.postgres.postgres_connection import PostgresConnection


load_dotenv(override=True)

RIOT_PERSONAL_API_KEY = os.getenv("LOL_PERSONAL_API_KEY")
POSTGRES_LOCAL_URL = os.getenv("POSTGRES_LOCAL_URL")
connection_wrapper = PostgresConnection(POSTGRES_LOCAL_URL)

In [2]:
_camel_case_regex = re.compile(
    r"(?<=[a-z])(?=[A-Z])"  # camelCase: survive|Min
    r"|(?<=[A-Z])(?=[A-Z][a-z])"  # acronym: HTML|Parser
    r"|(?<=[a-zA-Z])(?=\d)"  # letter→digit: survive|15
    r"|(?<=\d)(?=[a-zA-Z])"  # digit→letter: 15|min
)


def camel_to_snake(input_str: str) -> str:
    return _camel_case_regex.sub("_", input_str).lower()


def snake_all_keys(json_obj: dict):
    if isinstance(json_obj, dict):
        return {camel_to_snake(key): snake_all_keys(value) for key, value in json_obj.items()}

    if isinstance(json_obj, list):
        return [snake_all_keys(value) for value in json_obj]

    return json_obj

In [3]:
players = pl.read_database_uri("SELECT * FROM players", POSTGRES_LOCAL_URL)
players

shape: (3_100, 5)
┌──────────────────────────────┬──────────────────┬──────────┬────────┬────────────────────────────┐
│ puuid                        ┆ game_name        ┆ tag_line ┆ region ┆ synced_at                  │
│ ---                          ┆ ---              ┆ ---      ┆ ---    ┆ ---                        │
│ str                          ┆ str              ┆ str      ┆ str    ┆ datetime[μs]               │
╞══════════════════════════════╪══════════════════╪══════════╪════════╪════════════════════════════╡
│ x1jqYLksFHSjj-V_dTeZrzR9fFEV ┆ bird raven       ┆ 0000     ┆ EUN1   ┆ 2026-05-31 18:10:37.551072 │
│ Dt…                          ┆                  ┆          ┆        ┆                            │
│ QMPPN4oUrY-FW-BBOZ34yDZZmjgh ┆ KaizokuNoOni     ┆ 2829     ┆ EUN1   ┆ 2026-05-31 18:10:37.860377 │
│ Pa…                          ┆                  ┆          ┆        ┆                            │
│ yf1OVyzGtKFWKAh__NIUFtnEisdo ┆ Nolba            ┆ EUNE     ┆ EUN1   ┆ 2026-05-31 18:10:38.176115 │
│ hM…                          ┆                  ┆          ┆        ┆                            │
│ gw0udTm33m9cDPfENXndpjlXmkHw ┆ Defenser         ┆ EUNE     ┆ EUN1   ┆ 2026-05-31 18:10:38.472933 │
│ xl…                          ┆                  ┆          ┆        ┆                            │
│ tD8QYcsn9jmPaM7AACN9Id2fwgus ┆ Dioklis          ┆ EUNE     ┆ EUN1   ┆ 2026-05-31 18:10:38.757716 │
│ fN…                          ┆                  ┆          ┆        ┆                            │
│ …                            ┆ …                ┆ …        ┆ …      ┆ …                          │
│ dYiEC-ravKg74XNQMp4KsOp4S7aV ┆ black nails      ┆ 988      ┆ EUN1   ┆ 2026-05-31 19:15:39.289847 │
│ lR…                          ┆                  ┆          ┆        ┆                            │
│ ZLw_1J27yiyrFC_UN7-Uck-IyYMB ┆ AleEmotkaZostała ┆ RMJ      ┆ EUN1   ┆ 2026-05-31 19:15:39.630180 │
│ LL…                          ┆                  ┆          ┆        ┆                            │
│ 0CPr6RzHVit2UWf0Cu0EXPbIj77e ┆ chiefelo         ┆ 0314     ┆ EUN1   ┆ 2026-05-31 19:15:39.980448 │
│ ko…                          ┆                  ┆          ┆        ┆                            │
│ voxGacYDhQ3ptNab4tGe6ipPP3nZ ┆ Adam             ┆ RANK1    ┆ EUN1   ┆ 2026-05-31 19:15:40.353129 │
│ fc…                          ┆                  ┆          ┆        ┆                            │
│ eMwumb2gCUrYSrSf3D1t_9CyIv3k ┆ RAKIQ V NARGATA  ┆ WAGMI    ┆ EUN1   ┆ 2026-05-31 19:17:14.901659 │
│ PH…                          ┆                  ┆          ┆        ┆                            │
└──────────────────────────────┴──────────────────┴──────────┴────────┴────────────────────────────┘

In [25]:
from datetime import date


BASE_EUN1_URL = "https://eun1.api.riotgames.com"

headers = {
    'X-Riot-Token': RIOT_PERSONAL_API_KEY
}

def get_player_ranks(puuid: str):


    player_ranks_url=f"{BASE_EUN1_URL}/lol/league/v4/entries/by-puuid/{puuid}"
    response_ranks = requests.get(player_ranks_url,headers=headers)

    if response_ranks.status_code != 200:
        print("request failed with status code on getting player ranks", response_ranks.status_code)
        return response_ranks.status_code

    response_ranks_json = response_ranks.json()

    all_player_ranks = []

    for entry_ranks in response_ranks_json:
        player_ranks = {
            "puuid": puuid,
            "snapshot_date":date.today(),
            "queue_type": entry_ranks.get("queueType"),
            "tier": entry_ranks.get("tier"),
            "rank": entry_ranks.get("rank"),
            "league_points": entry_ranks.get("leaguePoints"),
            "wins": entry_ranks.get("wins"),
            "losses": entry_ranks.get("losses"),
            "hot_streak": entry_ranks.get("hotStreak"),
            "veteran": entry_ranks.get("veteran"),
            "fresh_blood": entry_ranks.get("freshBlood"),
            "inactive": entry_ranks.get("inactive"),
        }
        all_player_ranks.append(player_ranks)

    return all_player_ranks


get_player_ranks(players["puuid"][0])

[{'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 27,
  'wins': 5,
  'losses': 13,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False}]

In [29]:
player_ranks_arr = []

current_index = 0
for player in players.iter_rows(named=True):
    current_index += 1
    if current_index % 50 == 0:
        print(f"progress {math.floor(current_index / len(players) * 100)}%")

    try:
        player_ranks = get_player_ranks(player["puuid"])
        while player_ranks == 429:
            print("retrying after getting rate limited")
            time.sleep(121)
            player_ranks = get_player_ranks(player["puuid"])

        player_ranks_arr.extend(player_ranks)

    except Exception as e:
        print(f"Error fetching snapshot for {player['puuid']}: {e}")
        continue

player_ranks_arr

progress 1%
progress 3%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 4%
progress 6%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 8%
progress 9%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 11%
progress 12%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 14%
progress 16%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 17%
progress 19%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 20%
progress 22%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 24%
progress 25%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 27%
progress 29%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 30%
progress 32%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 33%
progress 35%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 37%
progress 38%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 40%
progress 41%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 43%
progress 45%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 46%
progress 48%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 50%
progress 51%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 53%
progress 54%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 56%
progress 58%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 59%
progress 61%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 62%
progress 64%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 66%
progress 67%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 69%
progress 70%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 72%
progress 74%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 75%
progress 77%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 79%
progress 80%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 82%
progress 83%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 85%
progress 87%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 88%
progress 90%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 91%
progress 93%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 95%
progress 96%
request failed with status code on getting player ranks 429
retrying after getting rate limited
progress 98%
progress 100%

[{'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 27,
  'wins': 5,
  'losses': 13,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'QMPPN4oUrY-FW-BBOZ34yDZZmjghPaYoJqNongrmvIJJkD9MtNUvJG1FdgQcvywW23L_s_bA83HIWw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_FLEX_SR',
  'tier': 'SILVER',
  'rank': 'IV',
  'league_points': 42,
  'wins': 3,
  'losses': 2,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'QMPPN4oUrY-FW-BBOZ34yDZZmjghPaYoJqNongrmvIJJkD9MtNUvJG1FdgQcvywW23L_s_bA83HIWw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 60,
  'wins': 1,
  'losses': 4,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'yf1OVyzGtKFWKAh__NIUFtnEisdohMl-BIbvNfGtsk66yCvUNmURprF9LJxvD0s7X7w4FYOXxJtHig',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 71,
  'wins': 8,
  'losses': 11,
  'hot_streak': True,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'gw0udTm33m9cDPfENXndpjlXmkHwxlRKeeRlxptTMvXhMZin9UmJscHevIDj2CJX7RJTOiiaZ5X2SA',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 12,
  'wins': 1,
  'losses': 4,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'tD8QYcsn9jmPaM7AACN9Id2fwgusfN_aDOvKoJE6AUyeKzyrUoBOmXKYwBLSyvG2j_xFT5DnO6zUOA',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'IV',
  'league_points': 0,
  'wins': 29,
  'losses': 40,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': True,
  'inactive': False},
 {'puuid': 'Ex6oHbe6BQm-nlAGY5dG7OIq5x5MWpWiwDj5UadP7JYfHR4JPxUXlISDfSY6qOU3xFK-F-RtLj2mrw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 36,
  'wins': 138,
  'losses': 159,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'xlXYoWhWfkG96A8YPhWM4k5gN7Q2Z_GeVKUMR1tzXOMkJ3Ml4YGa4xThZJmfuF9q38p03JyE-CKZOQ',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 8,
  'wins': 7,
  'losses': 16,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': '-WvQ3AIG5_g1aDkg_QHQ-sbwo2P3ApYkF__fo2FsHgrCn8279YoaLDnSuCCMsexg42PetD1FtZedqA',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 21,
  'wins': 3,
  'losses': 11,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'NpnvbPm9mHNXrSzKBfMzxfPqfMVzIET9YNLO6OUE5c95ehbyKiFuc4ug4TglMAh1e6AyLgoiToZf3Q',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_FLEX_SR',
  'tier': 'BRONZE',
  'rank': 'IV',
  'league_points': 0,
  'wins': 4,
  'losses': 7,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'NpnvbPm9mHNXrSzKBfMzxfPqfMVzIET9YNLO6OUE5c95ehbyKiFuc4ug4TglMAh1e6AyLgoiToZf3Q',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 51,
  'wins': 31,
  'losses': 39,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'zr_Slr-EtH2JmkmH7TRaKP4aoMgzVYNjHwCdI8K-kWmtmP0mUMx305ZsomtHxEqqjciv7pCBmeieMQ',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 27,
  'wins': 1,
  'losses': 7,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'cmf9Wq4VPLC2kdxoVfNNUUnHDCTju0L-uXN85uQdd1BYfMyLmqWpkuHuhJJaUiKiN-9mVjjxcNsVwQ',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 75,
  'wins': 2,
  'losses': 5,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'CcG_Gnfaoc3Kmvta_hGfzj_hJboNG94m0GLz95UNtpv0ZWOajFwop-8evn51I95zUM7i_1FfEisuqA',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'IV',
  'league_points': 79,
  'wins': 104,
  'losses': 118,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': True,
  'inactive': False},
 {'puuid': 'q-EGxYoL0CmxyxkJXHauvq7nTad_poN_z6hxY9X9PaNIgYnxefV8Uvi2GlhR1Cvbr2cG8V-imPDarg',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_FLEX_SR',
  'tier': 'BRONZE',
  'rank': 'I',
  'league_points': 7,
  'wins': 9,
  'losses': 11,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'q-EGxYoL0CmxyxkJXHauvq7nTad_poN_z6hxY9X9PaNIgYnxefV8Uvi2GlhR1Cvbr2cG8V-imPDarg',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 12,
  'wins': 306,
  'losses': 326,
  'hot_streak': True,
  'veteran': False,
  'fresh_blood': True,
  'inactive': False},
 {'puuid': 'isSBTv0HLpPg8rDayF8OyHrhc_WZYm6kiIYQFNf_IzakV1Js2aoN6Wi5prSVfU7L8aisy-3DGn1_2g',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 53,
  'wins': 22,
  'losses': 36,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'ZPinSKzU_Wvya_v1HE63RzJ8EO1TU1_jJ1oxClgVXkV8PKjKcJ-sKDZSbZ7frYlQwsv8GDpQRZcyXQ',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 50,
  'wins': 7,
  'losses': 17,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': True,
  'inactive': False},
 {'puuid': 'Ucd7WsUkFVYCCTNzr61jnmG66VXrkIv1kkr8x20Upoo-S2Ku7SyDqvTtkTX48CCg7pJeoYa1Gpujyg',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 76,
  'wins': 2,
  'losses': 5,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'APtcQ7Yrb7feq6frECvN6Fe4xjUX4kh21UBs9wDZBJvvPVDPp6Y_jNg37aVxbUOybG1B15IIxg-_HQ',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 46,
  'wins': 17,
  'losses': 26,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': '_yS_49PEpnKhr8glwp4p6Vrllg3l2LKk0_MvUBKifb25SV7cdX2cJ0PzX1r7y9Cm9lh5xqHIm_IWyg',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 60,
  'wins': 3,
  'losses': 6,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'iVt4eEZIo_rBbddO4I_Khd_bZKKympzh4PwSL6Pu4MkyRadwtfmJCkkZdUXqfWFG4fhHPNlgL7DGxw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 68,
  'wins': 68,
  'losses': 85,
  'hot_streak': True,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'iVt4eEZIo_rBbddO4I_Khd_bZKKympzh4PwSL6Pu4MkyRadwtfmJCkkZdUXqfWFG4fhHPNlgL7DGxw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_FLEX_SR',
  'tier': 'SILVER',
  'rank': 'III',
  'league_points': 39,
  'wins': 2,
  'losses': 5,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': '6ItvcmArYTRCd4l-y0EmjH3F-WvgLFrlIb5W25k5h8whYP1ZE6irWwzgLTwKRZeSGbX6oidB8Sdhpw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 50,
  'wins': 1,
  'losses': 5,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'At6Rz1zHubpKmKfOUG44tLvCSgTTKUXS-Vk9aIK4BW5oF5r0nTGoA2HihImk9TYAbOTyrIV6kjaywQ',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 43,
  'wins': 31,
  'losses': 49,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'cYgOaFQ4BX96snjsmokXzsba5i70_jMZbEe_QcHAq7VXxCqmwcAr9FmyrqKJYWeiLwux2cb_09fPvA',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'IV',
  'league_points': 99,
  'wins': 34,
  'losses': 66,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': True,
  'inactive': False},
 {'puuid': 'Hil2k-BFBHJOX6_HwL412OrFT51bXq5wk0SihgZyRKJiJVAxovT8fxze38Evvj767rX0DuBRvykRyw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 42,
  'wins': 25,
  'losses': 37,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'CeRPqUHUdaae_wc0NdAUnUwsSpSlzP5B91Zo5gBCwuaAt6v86B6LiXMzEAw74aJQgg6ylvU78RUKxQ',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'BRONZE',
  'rank': 'IV',
  'league_points': 22,
  'wins': 24,
  'losses': 31,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': True,
  'inactive': False},
 {'puuid': 'CeRPqUHUdaae_wc0NdAUnUwsSpSlzP5B91Zo5gBCwuaAt6v86B6LiXMzEAw74aJQgg6ylvU78RUKxQ',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_FLEX_SR',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 3,
  'wins': 17,
  'losses': 30,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'Pry5fB1RwnffueYbPKXQmKvH8tfIyNawKaynghF8kFjR1pe_CgsiU76x-uBLJVQyYek24IlmcyRGng',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 61,
  'wins': 2,
  'losses': 5,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'R9LOtZA5nfnCd0nrWaSaaZB6_UBf2ESn-tSGRN9r0IeYHpf1roPXg13SmvGTx55-UJvf4hzPl367TA',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 46,
  'wins': 6,
  'losses': 12,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'eJaDR6eSdgdYQVrZUbQmZ8sc_VhOZJrhrKmXJQukN2RCctneZWHjVoEYbB01sGMQkiWet7J9ynnOGw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'II',
  'league_points': 79,
  'wins': 48,
  'losses': 72,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': True,
  'inactive': False},
 {'puuid': '0-ywEifYkSFBA640XHBQx74nrzA_G6Nx0QdS0hbCobejyT8Yn4Jb5uP6jFx7ebP9KffaDAbjsZWt6w',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_FLEX_SR',
  'tier': 'BRONZE',
  'rank': 'IV',
  'league_points': 17,
  'wins': 13,
  'losses': 12,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': '0-ywEifYkSFBA640XHBQx74nrzA_G6Nx0QdS0hbCobejyT8Yn4Jb5uP6jFx7ebP9KffaDAbjsZWt6w',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 12,
  'wins': 99,
  'losses': 135,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'vX6rti8CZL1QfJZbskooR-n-XLGyj_AKxQsfcGt01KEuy58azdGC1EjqNH2045ZTIz7bZEDkQ-eVmg',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 44,
  'wins': 1,
  'losses': 4,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'cu27xYBGOIeT05RgAEqv3WYScDhWi2LkSfpE-60GOEgyFvEbe3iUzbo-yYVU-DbcP2rL3PU-JbRH7Q',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 48,
  'wins': 1,
  'losses': 5,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'cu27xYBGOIeT05RgAEqv3WYScDhWi2LkSfpE-60GOEgyFvEbe3iUzbo-yYVU-DbcP2rL3PU-JbRH7Q',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_FLEX_SR',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 32,
  'wins': 1,
  'losses': 4,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'zRWiSBVddGJlRdMzkTQAFY_mA0lhzEXWUEUwKPrxfoFtg-V-yx_lmPmZVyDbFk2U6uNEUmqtNjFSaA',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 60,
  'wins': 1,
  'losses': 4,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'AeV_pnibHeIN8eoG5ilyiV63YG6Wd5I5GvqJJ1UZaPBC4TS9sPDtsDNs4QS6tfJUdaArBJ0kPlAChA',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 52,
  'wins': 1,
  'losses': 4,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'rOIPzJ_RXHZZE2kYN38Tgl5nFBWgp_O5uqbdW7E0qtoCyXCt0F8arMS3V4e6mVH6k_SJI3Cd313jAw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 69,
  'wins': 2,
  'losses': 5,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'JtYl21x-bZS10TZjvhQVy7vlTruN3uEh1bQKEOnrXt70zzo6rpFWvJfOKoQy46RPEOKBvsRdwgSQLg',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 55,
  'wins': 4,
  'losses': 8,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'fPQfDmULV0skrhoaxlau2uYMpN-1j_9_s2eXAMvLiCS63xQKVhzeIdOBSU77jzIzoyjPECkjfgNshw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 40,
  'wins': 4,
  'losses': 13,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'fTET4_-_Mt-Jte-CMzQf-yQ-JfPXy10xCLAIcYbZtkGye8q3Q0C3hBKl-cjc6rhE2EvVlWboCQKnlA',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 85,
  'wins': 3,
  'losses': 6,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'lDQYBoA7yRH0WDvmPy2rZlOdB3TCSJuI3vFdECawBIixlSsG1GnPiPTTeerlJ7etIea0c0c8rM2mRQ',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 24,
  'wins': 1,
  'losses': 5,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'k5uIBcKTnOzDXXzl_imwp0TW2bPZ-pPHDOx_2AMv8IIlweMXxO36-HkkwQIqxmO9MiEyoExP1szYiA',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 25,
  'wins': 2,
  'losses': 5,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'Jjvl4ZX6Fgxb3i_sLf7NnjR7K0NCfgLX2TQQpSRO0a1xnl9qMULtf24VjCUWvS6sNFAMzle9rfv2ow',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 58,
  'wins': 45,
  'losses': 57,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'YPVmkXRhCAFU5geb6K3w07zSJSr-l1nLLIEH-NtX-AA5PfsGU-jrwF9HJzlqyq8ke--pi-3LSnq0HA',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 72,
  'wins': 2,
  'losses': 4,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'Q2b4CORoeSzOmHQuWkWnO60EvXcxxjj6vh2sfTN_lJDdPSeEtKCS4AdASbwhBnwIPEE0GCvrK6Fbrw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 12,
  'wins': 1,
  'losses': 9,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'H7vARm5oeiOSeVICNzDt_SJfziTfQTiC6VReMCZ4MZ7g5wMdL4Xsx5BTcnqKNqnymcuoTOjsRCfciQ',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 47,
  'wins': 2,
  'losses': 6,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'l36iy8cZBY7KfSqtCUc121Y9Dxp6710nmA6MKz7Kl24t_rkKmc-22LS9D1oF7qqQIsWiOkWW3DjUTw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 44,
  'wins': 13,
  'losses': 22,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'l36iy8cZBY7KfSqtCUc121Y9Dxp6710nmA6MKz7Kl24t_rkKmc-22LS9D1oF7qqQIsWiOkWW3DjUTw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_FLEX_SR',
  'tier': 'IRON',
  'rank': 'II',
  'league_points': 61,
  'wins': 7,
  'losses': 19,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'mRW1gozSC6d7eus3CwnNpClr_VBoZBDnTEumaHzQf9gmesxS_-Zmaio9crdS8I7tB-PJ11NpqpBXdw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'II',
  'league_points': 94,
  'wins': 52,
  'losses': 67,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'LZKYcEbgoh2sxJy8fb0PtgITSU9zVZUFYiw7PtDEw_rXSxIAso7a6ipAUzHvoacy2oC74l0ec3kPbA',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 4,
  'wins': 3,
  'losses': 11,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': '-RQYuP6KubT0fQXlxRFH4xdhiToHVFUhZLNEXKVPAeBTM2eiO7QIN1Md1okT4o44QXDDBxzoLcP7SQ',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 16,
  'wins': 45,
  'losses': 64,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': True,
  'inactive': False},
 {'puuid': '-RQYuP6KubT0fQXlxRFH4xdhiToHVFUhZLNEXKVPAeBTM2eiO7QIN1Md1okT4o44QXDDBxzoLcP7SQ',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_FLEX_SR',
  'tier': 'BRONZE',
  'rank': 'II',
  'league_points': 25,
  'wins': 21,
  'losses': 20,
  'hot_streak': True,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'LQBPV0etynRTa9mHm-o_gdD5InlhFUvxa5a6GUByDkIWej8IIfFF-NRstOjby6GZIlYbXa4OHrtyUw',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 51,
  'wins': 3,
  'losses': 11,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'Y_4A_i2DKrkgijyu77OUCV_kCoJbxIg7loFsX-sLk0_SHyAEynHAuOLokv95OgEtNMkkW16NwmvK3g',
  'snapshot_date': datetime.date(2026, 6, 3),
  'queue_type': 'RANKED_SOLO_5x5',
  'tier': 'IRON',
  'rank': 'I',
  'league_points': 60,
  'wins': 1,
  'losses': 4,
  'hot_streak': False,
  'veteran': False,
  'fresh_blood': False,
  'inactive': False},
 {'puuid': 'mt9T7L1-wGWekbBU4wzDDT5RGRV3YaVrUe_sAnMGxv91NAyeNqvN0CEuE2pEAt-ZB7DM-o9qW3aoXQ',
  'snapshot_date': datetime.date(2026, 6, 3),

In [30]:
print(player_ranks_arr)

[{'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 27, 'wins': 5, 'losses': 13, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'QMPPN4oUrY-FW-BBOZ34yDZZmjghPaYoJqNongrmvIJJkD9MtNUvJG1FdgQcvywW23L_s_bA83HIWw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_FLEX_SR', 'tier': 'SILVER', 'rank': 'IV', 'league_points': 42, 'wins': 3, 'losses': 2, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'QMPPN4oUrY-FW-BBOZ34yDZZmjghPaYoJqNongrmvIJJkD9MtNUvJG1FdgQcvywW23L_s_bA83HIWw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 60, 'wins': 1, 'losses': 4, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'yf1OVyzGtKFWKAh__NIUFtnEisdohMl-BIbvNfGtsk66yCvUNmURprF9LJxvD0s7X7w4FYOXxJtHig', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 71, 'wins': 8, 'losses': 11, 'hot_streak': True, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'gw0udTm33m9cDPfENXndpjlXmkHwxlRKeeRlxptTMvXhMZin9UmJscHevIDj2CJX7RJTOiiaZ5X2SA', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 12, 'wins': 1, 'losses': 4, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'tD8QYcsn9jmPaM7AACN9Id2fwgusfN_aDOvKoJE6AUyeKzyrUoBOmXKYwBLSyvG2j_xFT5DnO6zUOA', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'BRONZE', 'rank': 'IV', 'league_points': 0, 'wins': 29, 'losses': 40, 'hot_streak': False, 'veteran': False, 'fresh_blood': True, 'inactive': False}, {'puuid': 'Ex6oHbe6BQm-nlAGY5dG7OIq5x5MWpWiwDj5UadP7JYfHR4JPxUXlISDfSY6qOU3xFK-F-RtLj2mrw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 36, 'wins': 138, 'losses': 159, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'xlXYoWhWfkG96A8YPhWM4k5gN7Q2Z_GeVKUMR1tzXOMkJ3Ml4YGa4xThZJmfuF9q38p03JyE-CKZOQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 8, 'wins': 7, 'losses': 16, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': '-WvQ3AIG5_g1aDkg_QHQ-sbwo2P3ApYkF__fo2FsHgrCn8279YoaLDnSuCCMsexg42PetD1FtZedqA', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 21, 'wins': 3, 'losses': 11, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'NpnvbPm9mHNXrSzKBfMzxfPqfMVzIET9YNLO6OUE5c95ehbyKiFuc4ug4TglMAh1e6AyLgoiToZf3Q', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_FLEX_SR', 'tier': 'BRONZE', 'rank': 'IV', 'league_points': 0, 'wins': 4, 'losses': 7, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'NpnvbPm9mHNXrSzKBfMzxfPqfMVzIET9YNLO6OUE5c95ehbyKiFuc4ug4TglMAh1e6AyLgoiToZf3Q', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 51, 'wins': 31, 'losses': 39, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'zr_Slr-EtH2JmkmH7TRaKP4aoMgzVYNjHwCdI8K-kWmtmP0mUMx305ZsomtHxEqqjciv7pCBmeieMQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 27, 'wins': 1, 'losses': 7, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'cmf9Wq4VPLC2kdxoVfNNUUnHDCTju0L-uXN85uQdd1BYfMyLmqWpkuHuhJJaUiKiN-9mVjjxcNsVwQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 75, 'wins': 2, 'losses': 5, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'CcG_Gnfaoc3Kmvta_hGfzj_hJboNG94m0GLz95UNtpv0ZWOajFwop-8evn51I95zUM7i_1FfEisuqA', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'BRONZE', 'rank': 'IV', 'league_points': 79, 'wins': 104, 'losses': 118, 'hot_streak': False, 'veteran': False, 'fresh_blood': True, 'inactive': False}, {'puuid': 'q-EGxYoL0CmxyxkJXHauvq7nTad_poN_z6hxY9X9PaNIgYnxefV8Uvi2GlhR1Cvbr2cG8V-imPDarg', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_FLEX_SR', 'tier': 'BRONZE', 'rank': 'I', 'league_points': 7, 'wins': 9, 'losses': 11, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'q-EGxYoL0CmxyxkJXHauvq7nTad_poN_z6hxY9X9PaNIgYnxefV8Uvi2GlhR1Cvbr2cG8V-imPDarg', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 12, 'wins': 306, 'losses': 326, 'hot_streak': True, 'veteran': False, 'fresh_blood': True, 'inactive': False}, {'puuid': 'isSBTv0HLpPg8rDayF8OyHrhc_WZYm6kiIYQFNf_IzakV1Js2aoN6Wi5prSVfU7L8aisy-3DGn1_2g', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 53, 'wins': 22, 'losses': 36, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'ZPinSKzU_Wvya_v1HE63RzJ8EO1TU1_jJ1oxClgVXkV8PKjKcJ-sKDZSbZ7frYlQwsv8GDpQRZcyXQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 50, 'wins': 7, 'losses': 17, 'hot_streak': False, 'veteran': False, 'fresh_blood': True, 'inactive': False}, {'puuid': 'Ucd7WsUkFVYCCTNzr61jnmG66VXrkIv1kkr8x20Upoo-S2Ku7SyDqvTtkTX48CCg7pJeoYa1Gpujyg', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 76, 'wins': 2, 'losses': 5, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'APtcQ7Yrb7feq6frECvN6Fe4xjUX4kh21UBs9wDZBJvvPVDPp6Y_jNg37aVxbUOybG1B15IIxg-_HQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 46, 'wins': 17, 'losses': 26, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': '_yS_49PEpnKhr8glwp4p6Vrllg3l2LKk0_MvUBKifb25SV7cdX2cJ0PzX1r7y9Cm9lh5xqHIm_IWyg', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 60, 'wins': 3, 'losses': 6, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'iVt4eEZIo_rBbddO4I_Khd_bZKKympzh4PwSL6Pu4MkyRadwtfmJCkkZdUXqfWFG4fhHPNlgL7DGxw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 68, 'wins': 68, 'losses': 85, 'hot_streak': True, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'iVt4eEZIo_rBbddO4I_Khd_bZKKympzh4PwSL6Pu4MkyRadwtfmJCkkZdUXqfWFG4fhHPNlgL7DGxw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_FLEX_SR', 'tier': 'SILVER', 'rank': 'III', 'league_points': 39, 'wins': 2, 'losses': 5, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': '6ItvcmArYTRCd4l-y0EmjH3F-WvgLFrlIb5W25k5h8whYP1ZE6irWwzgLTwKRZeSGbX6oidB8Sdhpw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 50, 'wins': 1, 'losses': 5, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'At6Rz1zHubpKmKfOUG44tLvCSgTTKUXS-Vk9aIK4BW5oF5r0nTGoA2HihImk9TYAbOTyrIV6kjaywQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 43, 'wins': 31, 'losses': 49, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'cYgOaFQ4BX96snjsmokXzsba5i70_jMZbEe_QcHAq7VXxCqmwcAr9FmyrqKJYWeiLwux2cb_09fPvA', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'IV', 'league_points': 99, 'wins': 34, 'losses': 66, 'hot_streak': False, 'veteran': False, 'fresh_blood': True, 'inactive': False}, {'puuid': 'Hil2k-BFBHJOX6_HwL412OrFT51bXq5wk0SihgZyRKJiJVAxovT8fxze38Evvj767rX0DuBRvykRyw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 42, 'wins': 25, 'losses': 37, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'CeRPqUHUdaae_wc0NdAUnUwsSpSlzP5B91Zo5gBCwuaAt6v86B6LiXMzEAw74aJQgg6ylvU78RUKxQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'BRONZE', 'rank': 'IV', 'league_points': 22, 'wins': 24, 'losses': 31, 'hot_streak': False, 'veteran': False, 'fresh_blood': True, 'inactive': False}, {'puuid': 'CeRPqUHUdaae_wc0NdAUnUwsSpSlzP5B91Zo5gBCwuaAt6v86B6LiXMzEAw74aJQgg6ylvU78RUKxQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_FLEX_SR', 'tier': 'IRON', 'rank': 'I', 'league_points': 3, 'wins': 17, 'losses': 30, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'Pry5fB1RwnffueYbPKXQmKvH8tfIyNawKaynghF8kFjR1pe_CgsiU76x-uBLJVQyYek24IlmcyRGng', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 61, 'wins': 2, 'losses': 5, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'R9LOtZA5nfnCd0nrWaSaaZB6_UBf2ESn-tSGRN9r0IeYHpf1roPXg13SmvGTx55-UJvf4hzPl367TA', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 46, 'wins': 6, 'losses': 12, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'eJaDR6eSdgdYQVrZUbQmZ8sc_VhOZJrhrKmXJQukN2RCctneZWHjVoEYbB01sGMQkiWet7J9ynnOGw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'II', 'league_points': 79, 'wins': 48, 'losses': 72, 'hot_streak': False, 'veteran': False, 'fresh_blood': True, 'inactive': False}, {'puuid': '0-ywEifYkSFBA640XHBQx74nrzA_G6Nx0QdS0hbCobejyT8Yn4Jb5uP6jFx7ebP9KffaDAbjsZWt6w', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_FLEX_SR', 'tier': 'BRONZE', 'rank': 'IV', 'league_points': 17, 'wins': 13, 'losses': 12, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': '0-ywEifYkSFBA640XHBQx74nrzA_G6Nx0QdS0hbCobejyT8Yn4Jb5uP6jFx7ebP9KffaDAbjsZWt6w', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 12, 'wins': 99, 'losses': 135, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'vX6rti8CZL1QfJZbskooR-n-XLGyj_AKxQsfcGt01KEuy58azdGC1EjqNH2045ZTIz7bZEDkQ-eVmg', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 44, 'wins': 1, 'losses': 4, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'cu27xYBGOIeT05RgAEqv3WYScDhWi2LkSfpE-60GOEgyFvEbe3iUzbo-yYVU-DbcP2rL3PU-JbRH7Q', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 48, 'wins': 1, 'losses': 5, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'cu27xYBGOIeT05RgAEqv3WYScDhWi2LkSfpE-60GOEgyFvEbe3iUzbo-yYVU-DbcP2rL3PU-JbRH7Q', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_FLEX_SR', 'tier': 'IRON', 'rank': 'I', 'league_points': 32, 'wins': 1, 'losses': 4, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'zRWiSBVddGJlRdMzkTQAFY_mA0lhzEXWUEUwKPrxfoFtg-V-yx_lmPmZVyDbFk2U6uNEUmqtNjFSaA', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 60, 'wins': 1, 'losses': 4, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'AeV_pnibHeIN8eoG5ilyiV63YG6Wd5I5GvqJJ1UZaPBC4TS9sPDtsDNs4QS6tfJUdaArBJ0kPlAChA', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 52, 'wins': 1, 'losses': 4, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'rOIPzJ_RXHZZE2kYN38Tgl5nFBWgp_O5uqbdW7E0qtoCyXCt0F8arMS3V4e6mVH6k_SJI3Cd313jAw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 69, 'wins': 2, 'losses': 5, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'JtYl21x-bZS10TZjvhQVy7vlTruN3uEh1bQKEOnrXt70zzo6rpFWvJfOKoQy46RPEOKBvsRdwgSQLg', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 55, 'wins': 4, 'losses': 8, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'fPQfDmULV0skrhoaxlau2uYMpN-1j_9_s2eXAMvLiCS63xQKVhzeIdOBSU77jzIzoyjPECkjfgNshw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 40, 'wins': 4, 'losses': 13, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'fTET4_-_Mt-Jte-CMzQf-yQ-JfPXy10xCLAIcYbZtkGye8q3Q0C3hBKl-cjc6rhE2EvVlWboCQKnlA', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 85, 'wins': 3, 'losses': 6, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'lDQYBoA7yRH0WDvmPy2rZlOdB3TCSJuI3vFdECawBIixlSsG1GnPiPTTeerlJ7etIea0c0c8rM2mRQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 24, 'wins': 1, 'losses': 5, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'k5uIBcKTnOzDXXzl_imwp0TW2bPZ-pPHDOx_2AMv8IIlweMXxO36-HkkwQIqxmO9MiEyoExP1szYiA', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 25, 'wins': 2, 'losses': 5, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'Jjvl4ZX6Fgxb3i_sLf7NnjR7K0NCfgLX2TQQpSRO0a1xnl9qMULtf24VjCUWvS6sNFAMzle9rfv2ow', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 58, 'wins': 45, 'losses': 57, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'YPVmkXRhCAFU5geb6K3w07zSJSr-l1nLLIEH-NtX-AA5PfsGU-jrwF9HJzlqyq8ke--pi-3LSnq0HA', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 72, 'wins': 2, 'losses': 4, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'Q2b4CORoeSzOmHQuWkWnO60EvXcxxjj6vh2sfTN_lJDdPSeEtKCS4AdASbwhBnwIPEE0GCvrK6Fbrw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 12, 'wins': 1, 'losses': 9, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'H7vARm5oeiOSeVICNzDt_SJfziTfQTiC6VReMCZ4MZ7g5wMdL4Xsx5BTcnqKNqnymcuoTOjsRCfciQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 47, 'wins': 2, 'losses': 6, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'l36iy8cZBY7KfSqtCUc121Y9Dxp6710nmA6MKz7Kl24t_rkKmc-22LS9D1oF7qqQIsWiOkWW3DjUTw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 44, 'wins': 13, 'losses': 22, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'l36iy8cZBY7KfSqtCUc121Y9Dxp6710nmA6MKz7Kl24t_rkKmc-22LS9D1oF7qqQIsWiOkWW3DjUTw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_FLEX_SR', 'tier': 'IRON', 'rank': 'II', 'league_points': 61, 'wins': 7, 'losses': 19, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'mRW1gozSC6d7eus3CwnNpClr_VBoZBDnTEumaHzQf9gmesxS_-Zmaio9crdS8I7tB-PJ11NpqpBXdw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'II', 'league_points': 94, 'wins': 52, 'losses': 67, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'LZKYcEbgoh2sxJy8fb0PtgITSU9zVZUFYiw7PtDEw_rXSxIAso7a6ipAUzHvoacy2oC74l0ec3kPbA', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 4, 'wins': 3, 'losses': 11, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': '-RQYuP6KubT0fQXlxRFH4xdhiToHVFUhZLNEXKVPAeBTM2eiO7QIN1Md1okT4o44QXDDBxzoLcP7SQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 16, 'wins': 45, 'losses': 64, 'hot_streak': False, 'veteran': False, 'fresh_blood': True, 'inactive': False}, {'puuid': '-RQYuP6KubT0fQXlxRFH4xdhiToHVFUhZLNEXKVPAeBTM2eiO7QIN1Md1okT4o44QXDDBxzoLcP7SQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_FLEX_SR', 'tier': 'BRONZE', 'rank': 'II', 'league_points': 25, 'wins': 21, 'losses': 20, 'hot_streak': True, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'LQBPV0etynRTa9mHm-o_gdD5InlhFUvxa5a6GUByDkIWej8IIfFF-NRstOjby6GZIlYbXa4OHrtyUw', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 51, 'wins': 3, 'losses': 11, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'Y_4A_i2DKrkgijyu77OUCV_kCoJbxIg7loFsX-sLk0_SHyAEynHAuOLokv95OgEtNMkkW16NwmvK3g', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 60, 'wins': 1, 'losses': 4, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'mt9T7L1-wGWekbBU4wzDDT5RGRV3YaVrUe_sAnMGxv91NAyeNqvN0CEuE2pEAt-ZB7DM-o9qW3aoXQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 54, 'wins': 23, 'losses': 30, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'qWl20Hs9MMa9RcoGtzXEA3QuEn1oEaUjNMsMHAfEszT4YxdM0lZ-aPf-f31Lsm0Re6xrMaVZIORG8g', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 5, 'wins': 49, 'losses': 76, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'Yv0HMHPs1YDNcYhRJC4i39e2xmCVVfQ7GBZ0T6hXB3saXPp__02q0yxU8FTgdTIa36z1uYFzwwEsWg', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 16, 'wins': 45, 'losses': 64, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': 'twd7Ns30GevhNbOAOBhpnHXchhUF7NtLRHBWTEG8S1s_jgILf1yyZkNq800NzUDWvxAT6n0YddB_VQ', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x5', 'tier': 'IRON', 'rank': 'I', 'league_points': 11, 'wins': 7, 'losses': 18, 'hot_streak': False, 'veteran': False, 'fresh_blood': False, 'inactive': False}, {'puuid': '61dxAwpmqJjHmDRHJv1-j7K5P1fJUogyUqxO8LcOav35Rl8g_E13Ki9Qc2rrAbV4u7BfoXnsb6nO_g', 'snapshot_date': datetime.date(2026, 6, 3), 'queue_type': 'RANKED_SOLO_5x

In [39]:
player_ranks_df=pl.DataFrame(player_ranks_arr)
player_ranks_df = player_ranks_df.with_columns(
    pl.lit(date(2026, 6, 2)).alias("snapshot_date")
)
player_ranks_df

shape: (4_403, 12)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬──────────┐
│ puuid      ┆ snapshot_d ┆ queue_typ ┆ tier      ┆ … ┆ hot_strea ┆ veteran ┆ fresh_blo ┆ inactive │
│ ---        ┆ ate        ┆ e         ┆ ---       ┆   ┆ k         ┆ ---     ┆ od        ┆ ---      │
│ str        ┆ ---        ┆ ---       ┆ str       ┆   ┆ ---       ┆ bool    ┆ ---       ┆ bool     │
│            ┆ date       ┆ str       ┆           ┆   ┆ bool      ┆         ┆ bool      ┆          │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪══════════╡
│ x1jqYLksFH ┆ 2026-06-02 ┆ RANKED_SO ┆ IRON      ┆ … ┆ false     ┆ false   ┆ false     ┆ false    │
│ Sjj-V_dTeZ ┆            ┆ LO_5x5    ┆           ┆   ┆           ┆         ┆           ┆          │
│ rzR9fFEVDt ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ …          ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ QMPPN4oUrY ┆ 2026-06-02 ┆ RANKED_FL ┆ SILVER    ┆ … ┆ false     ┆ false   ┆ false     ┆ false    │
│ -FW-BBOZ34 ┆            ┆ EX_SR     ┆           ┆   ┆           ┆         ┆           ┆          │
│ yDZZmjghPa ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ …          ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ QMPPN4oUrY ┆ 2026-06-02 ┆ RANKED_SO ┆ IRON      ┆ … ┆ false     ┆ false   ┆ false     ┆ false    │
│ -FW-BBOZ34 ┆            ┆ LO_5x5    ┆           ┆   ┆           ┆         ┆           ┆          │
│ yDZZmjghPa ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ …          ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ yf1OVyzGtK ┆ 2026-06-02 ┆ RANKED_SO ┆ IRON      ┆ … ┆ true      ┆ false   ┆ false     ┆ false    │
│ FWKAh__NIU ┆            ┆ LO_5x5    ┆           ┆   ┆           ┆         ┆           ┆          │
│ FtnEisdohM ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ …          ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ gw0udTm33m ┆ 2026-06-02 ┆ RANKED_SO ┆ IRON      ┆ … ┆ false     ┆ false   ┆ false     ┆ false    │
│ 9cDPfENXnd ┆            ┆ LO_5x5    ┆           ┆   ┆           ┆         ┆           ┆          │
│ pjlXmkHwxl ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ …          ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …        │
│ ZLw_1J27yi ┆ 2026-06-02 ┆ RANKED_FL ┆ EMERALD   ┆ … ┆ false     ┆ false   ┆ false     ┆ false    │
│ yrFC_UN7-U ┆            ┆ EX_SR     ┆           ┆   ┆           ┆         ┆           ┆          │
│ ck-IyYMBLL ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ …          ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ 0CPr6RzHVi ┆ 2026-06-02 ┆ RANKED_SO ┆ CHALLENGE ┆ … ┆ false     ┆ false   ┆ false     ┆ false    │
│ t2UWf0Cu0E ┆            ┆ LO_5x5    ┆ R         ┆   ┆           ┆         ┆           ┆          │
│ XPbIj77eko ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ …          ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ voxGacYDhQ ┆ 2026-06-02 ┆ RANKED_FL ┆ MASTER    ┆ … ┆ false     ┆ false   ┆ false     ┆ false    │
│ 3ptNab4tGe ┆            ┆ EX_SR     ┆           ┆   ┆           ┆         ┆           ┆          │
│ 6ipPP3nZfc ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ …          ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ voxGacYDhQ ┆ 2026-06-02 ┆ RANKED_SO ┆ CHALLENGE ┆ … ┆ false     ┆ false   ┆ true      ┆ false    │
│ 3ptNab4tGe ┆            ┆ LO_5x5    ┆ R         ┆   ┆           ┆         ┆           ┆          │
│ 6ipPP3nZfc ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ …          ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ eMwumb2gCU ┆ 2026-06-02 ┆ RANKED_SO ┆ CHALLENGE ┆ … ┆ false     ┆ false   ┆ true      ┆ false    │
│ rYSrSf3D1t ┆            ┆ LO_5x5    ┆ R         ┆   ┆           ┆         ┆           ┆          │
│ _9CyIv3kPH ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
│ …          ┆            ┆           ┆           ┆   ┆           ┆         ┆           ┆          │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴──────────┘

In [41]:
from utils.postgres.postgres_connection import PostgresConnection
connection_wrapper = PostgresConnection(POSTGRES_LOCAL_URL)

opening connection

In [42]:
connection_wrapper.upsert_dataframe_dto_safe(player_ranks_df, "ranks", ["puuid","queue_type","snapshot_date"])

0

In [36]:
player_ranks_df.write_parquet("ranks.parquet")