In [46]:
import os
from dotenv import load_dotenv

load_dotenv(override=True)


RIOT_PERSONAL_API_KEY = os.getenv("LOL_PERSONAL_API_KEY")
POSTGRES_LOCAL_URL = os.getenv("POSTGRES_LOCAL_URL")

from utils.postgres.postgres_connection import PostgresConnection
connection_wrapper = PostgresConnection(POSTGRES_LOCAL_URL)

opening connection

In [2]:
import requests

url = "https://eun1.api.riotgames.com/lol/champion-mastery/v4/champion-masteries/by-puuid/sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg"

headers = {"x-riot-token": RIOT_PERSONAL_API_KEY}

response = requests.get(url, headers=headers)

print(response.json())

[{'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 203, 'championLevel': 111, 'championPoints': 1186858, 'lastPlayTime': 1780229451000, 'championPointsSinceLastLevel': 258, 'championPointsUntilNextLevel': 10742, 'markRequiredForNextLevel': 2, 'tokensEarned': 19, 'championSeasonMilestone': 8, 'milestoneGrades': ['S+', 'A+'], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 2}, 'rewardMarks': 1, 'bonus': True, 'totalGamesRequires': 2}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 55, 'championLevel': 39, 'championPoints': 429422, 'lastPlayTime': 1779820251000, 'championPointsSinceLastLevel': 34822, 'championPointsUntilNextLevel': -23822, 'markRequiredForNextLevel': 2, 'tokensEarned': 0, 'championSeasonMilestone': 2, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 1}, 'rewardMarks': 2, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 121, 'championLevel': 33, 'championPoints': 334516, 'lastPlayTime': 1780695969000, 'championPointsSinceLastLevel': 5916, 'championPointsUntilNextLevel': 5084, 'markRequiredForNextLevel': 2, 'tokensEarned': 16, 'championSeasonMilestone': 6, 'milestoneGrades': ['B', 'D+', 'A+', 'A+', 'A', 'S', 'A', 'A+', 'A+', 'B+', 'B+', 'A', 'A', 'A'], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 2}, 'rewardMarks': 1, 'bonus': True, 'totalGamesRequires': 2}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 141, 'championLevel': 28, 'championPoints': 278419, 'lastPlayTime': 1780429256000, 'championPointsSinceLastLevel': 4819, 'championPointsUntilNextLevel': 6181, 'markRequiredForNextLevel': 2, 'tokensEarned': 20, 'championSeasonMilestone': 8, 'milestoneGrades': ['B+', 'S+'], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 2}, 'rewardMarks': 1, 'bonus': True, 'totalGamesRequires': 2}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 131, 'championLevel': 18, 'championPoints': 172449, 'lastPlayTime': 1780175285000, 'championPointsSinceLastLevel': 8849, 'championPointsUntilNextLevel': 2151, 'markRequiredForNextLevel': 2, 'tokensEarned': 4, 'championSeasonMilestone': 4, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 2}, 'rewardMarks': 1, 'bonus': True, 'totalGamesRequires': 2}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 498, 'championLevel': 15, 'championPoints': 168886, 'lastPlayTime': 1780150053000, 'championPointsSinceLastLevel': 38286, 'championPointsUntilNextLevel': -27286, 'markRequiredForNextLevel': 2, 'tokensEarned': 0, 'championSeasonMilestone': 0, 'milestoneGrades': ['B'], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 238, 'championLevel': 12, 'championPoints': 139961, 'lastPlayTime': 1776880696000, 'championPointsSinceLastLevel': 42361, 'championPointsUntilNextLevel': -31361, 'markRequiredForNextLevel': 2, 'tokensEarned': 0, 'championSeasonMilestone': 0, 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 56, 'championLevel': 15, 'championPoints': 137565, 'lastPlayTime': 1777749085000, 'championPointsSinceLastLevel': 6965, 'championPointsUntilNextLevel': 4035, 'markRequiredForNextLevel': 2, 'tokensEarned': 4, 'championSeasonMilestone': 1, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 154, 'championLevel': 15, 'championPoints': 134776, 'lastPlayTime': 1756293452000, 'championPointsSinceLastLevel': 4176, 'championPointsUntilNextLevel': 6824, 'markRequiredForNextLevel': 2, 'tokensEarned': 0, 'championSeasonMilestone': 0, 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 32, 'championLevel': 13, 'championPoints': 111842, 'lastPlayTime': 1779011399000, 'championPointsSinceLastLevel': 3242, 'championPointsUntilNextLevel': 7758, 'markRequiredForNextLevel': 2, 'tokensEarned': 9, 'championSeasonMilestone': 1, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 412, 'championLevel': 12, 'championPoints': 105092, 'lastPlayTime': 1779449926000, 'championPointsSinceLastLevel': 7492, 'championPointsUntilNextLevel': 3508, 'markRequiredForNextLevel': 2, 'tokensEarned': 1, 'championSeasonMilestone': 2, 'milestoneGrades': ['C'], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 1}, 'rewardMarks': 2, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 245, 'championLevel': 11, 'championPoints': 91827, 'lastPlayTime': 1780083961000, 'championPointsSinceLastLevel': 5227, 'championPointsUntilNextLevel': 5773, 'markRequiredForNextLevel': 2, 'tokensEarned': 3, 'championSeasonMilestone': 2, 'milestoneGrades': ['A+'], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 1}, 'rewardMarks': 2, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 59, 'championLevel': 10, 'championPoints': 83874, 'lastPlayTime': 1750593392000, 'championPointsSinceLastLevel': 8274, 'championPointsUntilNextLevel': 2726, 'markRequiredForNextLevel': 2, 'tokensEarned': 3, 'championSeasonMilestone': 0, 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 33, 'championLevel': 10, 'championPoints': 83347, 'lastPlayTime': 1780177356000, 'championPointsSinceLastLevel': 7747, 'championPointsUntilNextLevel': 3253, 'markRequiredForNextLevel': 2, 'tokensEarned': 8, 'championSeasonMilestone': 2, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 1}, 'rewardMarks': 2, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 25, 'championLevel': 9, 'championPoints': 73777, 'lastPlayTime': 1779626884000, 'championPointsSinceLastLevel': 9177, 'championPointsUntilNextLevel': 1823, 'markRequiredForNextLevel': 2, 'tokensEarned': 17, 'championSeasonMilestone': 2, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 1}, 'rewardMarks': 2, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 63, 'championLevel': 9, 'championPoints': 72832, 'lastPlayTime': 1780598903000, 'championPointsSinceLastLevel': 8232, 'championPointsUntilNextLevel': 2768, 'markRequiredForNextLevel': 2, 'tokensEarned': 8, 'championSeasonMilestone': 2, 'milestoneGrades': ['B'], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 1}, 'rewardMarks': 2, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 142, 'championLevel': 9, 'championPoints': 68416, 'lastPlayTime': 1780431254000, 'championPointsSinceLastLevel': 3816, 'championPointsUntilNextLevel': 7184, 'markRequiredForNextLevel': 2, 'tokensEarned': 1, 'championSeasonMilestone': 1, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 254, 'championLevel': 9, 'championPoints': 66671, 'lastPlayTime': 1742683908000, 'championPointsSinceLastLevel': 2071, 'championPointsUntilNextLevel': 8929, 'markRequiredForNextLevel': 2, 'tokensEarned': 1, 'championSeasonMilestone': 0, 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 113, 'championLevel': 8, 'championPoints': 64301, 'lastPlayTime': 1780272589000, 'championPointsSinceLastLevel': 10701, 'championPointsUntilNextLevel': 299, 'markRequiredForNextLevel': 1, 'tokensEarned': 11, 'championSeasonMilestone': 2, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 1}, 'rewardMarks': 2, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 107, 'championLevel': 8, 'championPoints': 57010, 'lastPlayTime': 1755037982000, 'championPointsSinceLastLevel': 3410, 'championPointsUntilNextLevel': 7590, 'markRequiredForNextLevel': 1, 'tokensEarned': 0, 'championSeasonMilestone': 0, 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 69, 'championLevel': 7, 'championPoints': 56997, 'lastPlayTime': 1779454488000, 'championPointsSinceLastLevel': 14397, 'championPointsUntilNextLevel': -3397, 'markRequiredForNextLevel': 1, 'tokensEarned': 0, 'championSeasonMilestone': 0, 'milestoneGrades': ['C+'], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 876, 'championLevel': 8, 'championPoints': 55910, 'lastPlayTime': 1780151731000, 'championPointsSinceLastLevel': 2310, 'championPointsUntilNextLevel': 8690, 'markRequiredForNextLevel': 1, 'tokensEarned': 13, 'championSeasonMilestone': 2, 'milestoneGrades': ['B'], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 1}, 'rewardMarks': 2, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 134, 'championLevel': 8, 'championPoints': 55243, 'lastPlayTime': 1779023480000, 'championPointsSinceLastLevel': 1643, 'championPointsUntilNextLevel': 9357, 'markRequiredForNextLevel': 1, 'tokensEarned': 10, 'championSeasonMilestone': 1, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 234, 'championLevel': 8, 'championPoints': 54342, 'lastPlayTime': 1779641579000, 'championPointsSinceLastLevel': 742, 'championPointsUntilNextLevel': 10258, 'markRequiredForNextLevel': 1, 'tokensEarned': 4, 'championSeasonMilestone': 0, 'milestoneGrades': ['C'], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 222, 'championLevel': 8, 'championPoints': 53952, 'lastPlayTime': 1777288006000, 'championPointsSinceLastLevel': 352, 'championPointsUntilNextLevel': 10648, 'markRequiredForNextLevel': 1, 'tokensEarned': 2, 'championSeasonMilestone': 0, 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 157, 'championLevel': 8, 'championPoints': 53627, 'lastPlayTime': 1779543578000, 'championPointsSinceLastLevel': 27, 'championPointsUntilNextLevel': 10973, 'markRequiredForNextLevel': 1, 'tokensEarned': 2, 'championSeasonMilestone': 1, 'milestoneGrades': ['B', 'D+', 'C', 'C+'], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 24, 'championLevel': 7, 'championPoints': 48196, 'lastPlayTime': 1777716035000, 'championPointsSinceLastLevel': 5596, 'championPointsUntilNextLevel': 5404, 'markRequiredForNextLevel': 1, 'tokensEarned': 3, 'championSeasonMilestone': 1, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 17, 'championLevel': 7, 'championPoints': 48116, 'lastPlayTime': 1778782831000, 'championPointsSinceLastLevel': 5516, 'championPointsUntilNextLevel': 5484, 'markRequiredForNextLevel': 1, 'tokensEarned': 5, 'championSeasonMilestone': 1, 'milestoneGrades': ['B+'], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 235, 'championLevel': 7, 'championPoints': 48071, 'lastPlayTime': 1779452864000, 'championPointsSinceLastLevel': 5471, 'championPointsUntilNextLevel': 5529, 'markRequiredForNextLevel': 1, 'tokensEarned': 6, 'championSeasonMilestone': 2, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 1}, 'rewardMarks': 2, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 145, 'championLevel': 7, 'championPoints': 46995, 'lastPlayTime': 1779534071000, 'championPointsSinceLastLevel': 4395, 'championPointsUntilNextLevel': 6605, 'markRequiredForNextLevel': 1, 'tokensEarned': 2, 'championSeasonMilestone': 1, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 119, 'championLevel': 7, 'championPoints': 46894, 'lastPlayTime': 1780079654000, 'championPointsSinceLastLevel': 4294, 'championPointsUntilNextLevel': 6706, 'markRequiredForNextLevel': 1, 'tokensEarned': 6, 'championSeasonMilestone': 1, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 111, 'championLevel': 7, 'championPoints': 45784, 'lastPlayTime': 1779477954000, 'championPointsSinceLastLevel': 3184, 'championPointsUntilNextLevel': 7816, 'markRequiredForNextLevel': 1, 'tokensEarned': 11, 'championSeasonMilestone': 0, 'milestoneGrades': ['B'], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 429, 'championLevel': 7, 'championPoints': 44864, 'lastPlayTime': 1779740341000, 'championPointsSinceLastLevel': 2264, 'championPointsUntilNextLevel': 8736, 'markRequiredForNextLevel': 1, 'tokensEarned': 0, 'championSeasonMilestone': 1, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 86, 'championLevel': 7, 'championPoints': 43414, 'lastPlayTime': 1777209201000, 'championPointsSinceLastLevel': 814, 'championPointsUntilNextLevel': 10186, 'markRequiredForNextLevel': 1, 'tokensEarned': 3, 'championSeasonMilestone': 0, 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 53, 'championLevel': 7, 'championPoints': 43106, 'lastPlayTime': 1779628766000, 'championPointsSinceLastLevel': 506, 'championPointsUntilNextLevel': 10494, 'markRequiredForNextLevel': 1, 'tokensEarned': 1, 'championSeasonMilestone': 1, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 81, 'championLevel': 7, 'championPoints': 42793, 'lastPlayTime': 1779625618000, 'championPointsSinceLastLevel': 193, 'championPointsUntilNextLevel': 10807, 'markRequiredForNextLevel': 1, 'tokensEarned': 4, 'championSeasonMilestone': 1, 'milestoneGrades': [], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 8, 'championLevel': 6, 'championPoints': 39638, 'lastPlayTime': 1780059125000, 'championPointsSinceLastLevel': 8038, 'championPointsUntilNextLevel': 2962, 'markRequiredForNextLevel': 1, 'tokensEarned': 11, 'championSeasonMilestone': 0, 'milestoneGrades': ['C+', 'B', 'B+', 'B+'], 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 35, 'championLevel': 6, 'championPoints': 38688, 'lastPlayTime': 1779312043000, 'championPointsSinceLastLevel': 7088, 'championPointsUntilNextLevel': 3912, 'markRequiredForNextLevel': 1, 'tokensEarned': 9, 'championSeasonMilestone': 2, 'milestoneGrades': ['A'], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 1}, 'rewardMarks': 2, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 114, 'championLevel': 6, 'championPoints': 38492, 'lastPlayTime': 1742657474000, 'championPointsSinceLastLevel': 6892, 'championPointsUntilNextLevel': 4108, 'markRequiredForNextLevel': 1, 'tokensEarned': 1, 'championSeasonMilestone': 0, 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 75, 'championLevel': 6, 'championPoints': 38455, 'lastPlayTime': 1778606911000, 'championPointsSinceLastLevel': 6855, 'championPointsUntilNextLevel': 4145, 'markRequiredForNextLevel': 1, 'tokensEarned': 9, 'championSeasonMilestone': 2, 'milestoneGrades': ['B+'], 'nextSeasonMilestone': {'requireGradeCounts': {'S-': 1}, 'rewardMarks': 2, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 11, 'championLevel': 6, 'championPoints': 37985, 'lastPlayTime': 1738714667000, 'championPointsSinceLastLevel': 6385, 'championPointsUntilNextLevel': 4615, 'markRequiredForNextLevel': 1, 'tokensEarned': 2, 'championSeasonMilestone': 0, 'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1}, 'rewardMarks': 1, 'bonus': False, 'totalGamesRequires': 1}}, {'puuid': 'sTVEkAgV_YBpZI20HXfrBzzxcrpJuU4U4ZjNpzC-lrbb9nSgzrANhtk3BlF0ADpHX76maQUcxetBbg', 'championId': 105, 'championLevel': 6, 'championPoints': 35609, 'lastPlay

In [7]:
import polars as pl

df =  pl.read_database_uri(
    query= "SELECT puuid FROM players",
    uri = POSTGRES_LOCAL_URL,
)
df

shape: (3_100, 1)
┌─────────────────────────────────┐
│ puuid                           │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ x1jqYLksFHSjj-V_dTeZrzR9fFEVDt… │
│ QMPPN4oUrY-FW-BBOZ34yDZZmjghPa… │
│ yf1OVyzGtKFWKAh__NIUFtnEisdohM… │
│ gw0udTm33m9cDPfENXndpjlXmkHwxl… │
│ tD8QYcsn9jmPaM7AACN9Id2fwgusfN… │
│ …                               │
│ dYiEC-ravKg74XNQMp4KsOp4S7aVlR… │
│ ZLw_1J27yiyrFC_UN7-Uck-IyYMBLL… │
│ 0CPr6RzHVit2UWf0Cu0EXPbIj77eko… │
│ voxGacYDhQ3ptNab4tGe6ipPP3nZfc… │
│ eMwumb2gCUrYSrSf3D1t_9CyIv3kPH… │
└─────────────────────────────────┘

In [24]:
puuid_list = df["puuid"].to_list()[:10]
puuid_list

['x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
 'QMPPN4oUrY-FW-BBOZ34yDZZmjghPaYoJqNongrmvIJJkD9MtNUvJG1FdgQcvywW23L_s_bA83HIWw',
 'yf1OVyzGtKFWKAh__NIUFtnEisdohMl-BIbvNfGtsk66yCvUNmURprF9LJxvD0s7X7w4FYOXxJtHig',
 'gw0udTm33m9cDPfENXndpjlXmkHwxlRKeeRlxptTMvXhMZin9UmJscHevIDj2CJX7RJTOiiaZ5X2SA',
 'tD8QYcsn9jmPaM7AACN9Id2fwgusfN_aDOvKoJE6AUyeKzyrUoBOmXKYwBLSyvG2j_xFT5DnO6zUOA',
 'Ex6oHbe6BQm-nlAGY5dG7OIq5x5MWpWiwDj5UadP7JYfHR4JPxUXlISDfSY6qOU3xFK-F-RtLj2mrw',
 'xlXYoWhWfkG96A8YPhWM4k5gN7Q2Z_GeVKUMR1tzXOMkJ3Ml4YGa4xThZJmfuF9q38p03JyE-CKZOQ',
 '-WvQ3AIG5_g1aDkg_QHQ-sbwo2P3ApYkF__fo2FsHgrCn8279YoaLDnSuCCMsexg42PetD1FtZedqA',
 'NpnvbPm9mHNXrSzKBfMzxfPqfMVzIET9YNLO6OUE5c95ehbyKiFuc4ug4TglMAh1e6AyLgoiToZf3Q',
 'zr_Slr-EtH2JmkmH7TRaKP4aoMgzVYNjHwCdI8K-kWmtmP0mUMx305ZsomtHxEqqjciv7pCBmeieMQ']

In [41]:
json_collection = []

for puuid in puuid_list:
    url = f"https://eun1.api.riotgames.com/lol/champion-mastery/v4/champion-masteries/by-puuid/{puuid}"
    response = requests.get(url, headers=headers)
    json_collection.extend(response.json())
#df = pl.DataFrame(json_collection)
#df
json_collection

[{'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 121,
  'championLevel': 41,
  'championPoints': 438000,
  'lastPlayTime': 1773808057000,
  'championPointsSinceLastLevel': 21400,
  'championPointsUntilNextLevel': -10400,
  'markRequiredForNextLevel': 2,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 55,
  'championLevel': 10,
  'championPoints': 77126,
  'lastPlayTime': 1650386081000,
  'championPointsSinceLastLevel': 1526,
  'championPointsUntilNextLevel': 9474,
  'markRequiredForNextLevel': 2,
  'tokensEarned': 3,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 64,
  'championLevel': 7,
  'championPoints': 60830,
  'lastPlayTime': 1762217892000,
  'championPointsSinceLastLevel': 18230,
  'championPointsUntilNextLevel': -7230,
  'markRequiredForNextLevel': 1,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 11,
  'championLevel': 6,
  'championPoints': 48914,
  'lastPlayTime': 1773864189000,
  'championPointsSinceLastLevel': 17314,
  'championPointsUntilNextLevel': -6314,
  'markRequiredForNextLevel': 1,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 245,
  'championLevel': 7,
  'championPoints': 45626,
  'lastPlayTime': 1773969535000,
  'championPointsSinceLastLevel': 3026,
  'championPointsUntilNextLevel': 7974,
  'markRequiredForNextLevel': 1,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 53,
  'championLevel': 5,
  'championPoints': 28969,
  'lastPlayTime': 1690676018000,
  'championPointsSinceLastLevel': 7369,
  'championPointsUntilNextLevel': 2631,
  'markRequiredForNextLevel': 1,
  'tokensEarned': 1,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 104,
  'championLevel': 5,
  'championPoints': 27508,
  'lastPlayTime': 1658501268000,
  'championPointsSinceLastLevel': 5908,
  'championPointsUntilNextLevel': 4092,
  'markRequiredForNextLevel': 1,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 157,
  'championLevel': 4,
  'championPoints': 20444,
  'lastPlayTime': 1658507286000,
  'championPointsSinceLastLevel': 7844,
  'championPointsUntilNextLevel': 1156,
  'markRequiredForNextLevel': 1,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 32,
  'championLevel': 4,
  'championPoints': 16341,
  'lastPlayTime': 1690126687000,
  'championPointsSinceLastLevel': 3741,
  'championPointsUntilNextLevel': 5259,
  'markRequiredForNextLevel': 1,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 350,
  'championLevel': 4,
  'championPoints': 14545,
  'lastPlayTime': 1646358550000,
  'championPointsSinceLastLevel': 1945,
  'championPointsUntilNextLevel': 7055,
  'markRequiredForNextLevel': 1,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 28,
  'championLevel': 4,
  'championPoints': 13481,
  'lastPlayTime': 1657320600000,
  'championPointsSinceLastLevel': 881,
  'championPointsUntilNextLevel': 8119,
  'markRequiredForNextLevel': 1,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 20,
  'championLevel': 4,
  'championPoints': 12920,
  'lastPlayTime': 1659125168000,
  'championPointsSinceLastLevel': 320,
  'championPointsUntilNextLevel': 8680,
  'markRequiredForNextLevel': 1,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 105,
  'championLevel': 3,
  'championPoints': 7138,
  'lastPlayTime': 1647698496000,
  'championPointsSinceLastLevel': 1138,
  'championPointsUntilNextLevel': 5462,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 86,
  'championLevel': 2,
  'championPoints': 5970,
  'lastPlayTime': 1583274042000,
  'championPointsSinceLastLevel': 4170,
  'championPointsUntilNextLevel': 30,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 35,
  'championLevel': 2,
  'championPoints': 5590,
  'lastPlayTime': 1658523388000,
  'championPointsSinceLastLevel': 3790,
  'championPointsUntilNextLevel': 410,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 99,
  'championLevel': 2,
  'championPoints': 5087,
  'lastPlayTime': 1713055759000,
  'championPointsSinceLastLevel': 3287,
  'championPointsUntilNextLevel': 913,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 82,
  'championLevel': 2,
  'championPoints': 4894,
  'lastPlayTime': 1650580225000,
  'championPointsSinceLastLevel': 3094,
  'championPointsUntilNextLevel': 1106,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 84,
  'championLevel': 2,
  'championPoints': 4733,
  'lastPlayTime': 1647702486000,
  'championPointsSinceLastLevel': 2933,
  'championPointsUntilNextLevel': 1267,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 412,
  'championLevel': 2,
  'championPoints': 3562,
  'lastPlayTime': 1657142845000,
  'championPointsSinceLastLevel': 1762,
  'championPointsUntilNextLevel': 2438,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 45,
  'championLevel': 2,
  'championPoints': 3351,
  'lastPlayTime': 1644264365000,
  'championPointsSinceLastLevel': 1551,
  'championPointsUntilNextLevel': 2649,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 21,
  'championLevel': 2,
  'championPoints': 2352,
  'lastPlayTime': 1651856600000,
  'championPointsSinceLastLevel': 552,
  'championPointsUntilNextLevel': 3648,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 113,
  'championLevel': 2,
  'championPoints': 1954,
  'lastPlayTime': 1658615196000,
  'championPointsSinceLastLevel': 154,
  'championPointsUntilNextLevel': 4046,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 29,
  'championLevel': 1,
  'championPoints': 1252,
  'lastPlayTime': 1647969556000,
  'championPointsSinceLastLevel': 1252,
  'championPointsUntilNextLevel': 548,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 5,
  'championLevel': 1,
  'championPoints': 1203,
  'lastPlayTime': 1658939339000,
  'championPointsSinceLastLevel': 1203,
  'championPointsUntilNextLevel': 597,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 12,
  'championLevel': 1,
  'championPoints': 1117,
  'lastPlayTime': 1555751723000,
  'championPointsSinceLastLevel': 1117,
  'championPointsUntilNextLevel': 683,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 25,
  'championLevel': 1,
  'championPoints': 984,
  'lastPlayTime': 1648077768000,
  'championPointsSinceLastLevel': 984,
  'championPointsUntilNextLevel': 816,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 27,
  'championLevel': 1,
  'championPoints': 980,
  'lastPlayTime': 1650302649000,
  'championPointsSinceLastLevel': 980,
  'championPointsUntilNextLevel': 820,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 76,
  'championLevel': 1,
  'championPoints': 859,
  'lastPlayTime': 1647890710000,
  'championPointsSinceLastLevel': 859,
  'championPointsUntilNextLevel': 941,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 23,
  'championLevel': 1,
  'championPoints': 854,
  'lastPlayTime': 1650300575000,
  'championPointsSinceLastLevel': 854,
  'championPointsUntilNextLevel': 946,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 2,
  'championLevel': 1,
  'championPoints': 764,
  'lastPlayTime': 1647626433000,
  'championPointsSinceLastLevel': 764,
  'championPointsUntilNextLevel': 1036,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 98,
  'championLevel': 1,
  'championPoints': 512,
  'lastPlayTime': 1658609304000,
  'championPointsSinceLastLevel': 512,
  'championPointsUntilNextLevel': 1288,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 19,
  'championLevel': 1,
  'championPoints': 396,
  'lastPlayTime': 1593616100000,
  'championPointsSinceLastLevel': 396,
  'championPointsUntilNextLevel': 1404,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 15,
  'championLevel': 1,
  'championPoints': 393,
  'lastPlayTime': 1650296874000,
  'championPointsSinceLastLevel': 393,
  'championPointsUntilNextLevel': 1407,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 17,
  'championLevel': 1,
  'championPoints': 280,
  'lastPlayTime': 1658601895000,
  'championPointsSinceLastLevel': 280,
  'championPointsUntilNextLevel': 1520,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 141,
  'championLevel': 1,
  'championPoints': 277,
  'lastPlayTime': 1584392226000,
  'championPointsSinceLastLevel': 277,
  'championPointsUntilNextLevel': 1523,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 16,
  'championLevel': 1,
  'championPoints': 260,
  'lastPlayTime': 1582925717000,
  'championPointsSinceLastLevel': 260,
  'championPointsUntilNextLevel': 1540,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 22,
  'championLevel': 1,
  'championPoints': 186,
  'lastPlayTime': 1543251473000,
  'championPointsSinceLastLevel': 186,
  'championPointsUntilNextLevel': 1614,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 107,
  'championLevel': 1,
  'championPoints': 179,
  'lastPlayTime': 1595867544000,
  'championPointsSinceLastLevel': 179,
  'championPointsUntilNextLevel': 1621,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 106,
  'championLevel': 1,
  'championPoints': 158,
  'lastPlayTime': 1583193245000,
  'championPointsSinceLastLevel': 158,
  'championPointsUntilNextLevel': 1642,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'x1jqYLksFHSjj-V_dTeZrzR9fFEVDtcRFuZ0u9novIzvQW-QF-dE9YyTxsi08KU5rAUNccN9F2wLXQ',
  'championId': 24,
  'championLevel': 1,
  'championPoints': 156,
  'lastPlayTime': 1555616631000,
  'championPointsSinceLastLevel': 156,
  'championPointsUntilNextLevel': 1644,
  'markRequiredForNextLevel': 0,
  'tokensEarned': 0,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,
   'bonus': False,
   'totalGamesRequires': 1}},
 {'puuid': 'QMPPN4oUrY-FW-BBOZ34yDZZmjghPaYoJqNongrmvIJJkD9MtNUvJG1FdgQcvywW23L_s_bA83HIWw',
  'championId': 145,
  'championLevel': 10,
  'championPoints': 90368,
  'lastPlayTime': 1770152505000,
  'championPointsSinceLastLevel': 14768,
  'championPointsUntilNextLevel': -3768,
  'markRequiredForNextLevel': 2,
  'tokensEarned': 1,
  'championSeasonMilestone': 0,
  'nextSeasonMilestone': {'requireGradeCounts': {'A-': 1},
   'rewardMarks': 1,

In [47]:
from datetime import datetime,timezone
final_mastery_rows = []
def transform_row(row):
    return {
        "puuid": str(row["puuid"]),
        "champion_id": int(row["championId"]),
        "milestone_grades": row.get("milestoneGrades",[]),
        "tokens_earned": row["tokensEarned"],
        "champion_season_milestone": row["championSeasonMilestone"],
        "mark_required_for_next_level": row["markRequiredForNextLevel"],
        "champion_points_since_last_level": row["championPointsSinceLastLevel"],
        "champion_points": row["championPoints"],
        "champion_level": row["championLevel"],
        "last_play_time": datetime.fromtimestamp(row["lastPlayTime"] // 1000),
        "chest_granted": row.get("chestGranted"),#TODO: this is always null, potential fix SCHEMA
        "champion_points_until_next_level": row["championPointsUntilNextLevel"],
    }
for row in json_collection:
    final_mastery_rows.append(transform_row(row))
mastery_df = pl.DataFrame(final_mastery_rows)
mastery_df

shape: (856, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ puuid     ┆ champion_ ┆ milestone ┆ tokens_ea ┆ … ┆ champion_ ┆ last_play ┆ chest_gra ┆ champion │
│ ---       ┆ id        ┆ _grades   ┆ rned      ┆   ┆ level     ┆ _time     ┆ nted      ┆ _points_ │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ until_ne │
│           ┆ i64       ┆ list[str] ┆ i64       ┆   ┆ i64       ┆ datetime[ ┆ null      ┆ xt_lev…  │
│           ┆           ┆           ┆           ┆   ┆           ┆ μs]       ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ x1jqYLksF ┆ 121       ┆ []        ┆ 0         ┆ … ┆ 41        ┆ 2026-03-1 ┆ null      ┆ -10400   │
│ HSjj-V_dT ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆          │
│ eZrzR9fFE ┆           ┆           ┆           ┆   ┆           ┆ 06:27:37  ┆           ┆          │
│ VDt…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ x1jqYLksF ┆ 55        ┆ []        ┆ 3         ┆ … ┆ 10        ┆ 2022-04-1 ┆ null      ┆ 9474     │
│ HSjj-V_dT ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆          │
│ eZrzR9fFE ┆           ┆           ┆           ┆   ┆           ┆ 19:34:41  ┆           ┆          │
│ VDt…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ x1jqYLksF ┆ 64        ┆ []        ┆ 0         ┆ … ┆ 7         ┆ 2025-11-0 ┆ null      ┆ -7230    │
│ HSjj-V_dT ┆           ┆           ┆           ┆   ┆           ┆ 4         ┆           ┆          │
│ eZrzR9fFE ┆           ┆           ┆           ┆   ┆           ┆ 02:58:12  ┆           ┆          │
│ VDt…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ x1jqYLksF ┆ 11        ┆ []        ┆ 0         ┆ … ┆ 6         ┆ 2026-03-1 ┆ null      ┆ -6314    │
│ HSjj-V_dT ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆          │
│ eZrzR9fFE ┆           ┆           ┆           ┆   ┆           ┆ 22:03:09  ┆           ┆          │
│ VDt…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ x1jqYLksF ┆ 245       ┆ []        ┆ 0         ┆ … ┆ 7         ┆ 2026-03-2 ┆ null      ┆ 7974     │
│ HSjj-V_dT ┆           ┆           ┆           ┆   ┆           ┆ 0         ┆           ┆          │
│ eZrzR9fFE ┆           ┆           ┆           ┆   ┆           ┆ 03:18:55  ┆           ┆          │
│ VDt…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ zr_Slr-Et ┆ 78        ┆ []        ┆ 0         ┆ … ┆ 1         ┆ 2022-01-0 ┆ null      ┆ 1604     │
│ H2JmkmH7T ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆          │
│ RaKP4aoMg ┆           ┆           ┆           ┆   ┆           ┆ 18:20:57  ┆           ┆          │
│ zVY…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ zr_Slr-Et ┆ 85        ┆ []        ┆ 0         ┆ … ┆ 1         ┆ 2022-01-0 ┆ null      ┆ 1619     │
│ H2JmkmH7T ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆          │
│ RaKP4aoMg ┆           ┆           ┆           ┆   ┆           ┆ 18:20:57  ┆           ┆          │
│ zVY…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ zr_Slr-Et ┆ 34        ┆ []        ┆ 0         ┆ … ┆ 1         ┆ 2022-01-0 ┆ null      ┆ 1631     │
│ H2JmkmH7T ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆          │
│ RaKP4aoMg ┆           ┆           ┆           ┆   ┆           ┆ 18:20:57  ┆           ┆          │
│ zVY…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ zr_Slr-Et ┆ 80        ┆ []        ┆ 0         ┆ … ┆ 1         ┆ 2022-01-0 ┆ null      ┆ 1639     │
│ H2JmkmH7T ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆          │
│ RaKP4aoMg ┆           ┆           ┆           ┆   ┆           ┆ 18:20:57  ┆           ┆          │
│ zVY…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ zr_Slr-Et ┆ 23        ┆ []        ┆ 0         ┆ … ┆ 1         ┆ 2022-01-0 ┆ null      ┆ 1654     │
│ H2JmkmH7T ┆           ┆           ┆           ┆   ┆           ┆ 9         ┆           ┆          │
│ RaKP4aoMg ┆           ┆           ┆           ┆   ┆           ┆ 18:20:57  ┆           ┆          │
│ zVY…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [48]:
connection_wrapper.upsert_dataframe_dto_safe(mastery_df, "masteries", ["puuid", "champion_id"])

0